### ISSUE TITLE
Support Custom URLs

### ISSUE THREAD

**Issue by ChrisShumaker** [simple-salesforce/simple-salesforce#101]
Salesforce allows for URL customization but only standard instance domain/URL's are supported. There should be a way to specify the complete URL(s) on initialization.

**Comment by dbstraffin** [comment]
This feature would also be useful for writing e2e/functional tests using http://mock-server.com/ without having to change hosts files and putting mockserver on port 443.

I'd like to use what's in #102. Is there anything I can do to help get the PR merged and new release out?

**Comment by Shumakriss** [comment]
Hi @dbstraffin, @demianbrecht is a little backlogged merging PR's at the moment so I want to prep the PR to make this as easy as possible.

I am posting some comments about what we need to do on the PR #102 if you want to check them out.

**Comment by espoelstra** [comment]
I believe this has been implemented with the `domain=` functionality?

**Comment by thommor** [comment]
Closing due to this having already been implemented
