### ISSUE TITLE
Salesforce and TLSv1.1

### ISSUE THREAD

**Issue by calpaterson** [simple-salesforce/simple-salesforce#103]
Soon [Salesforce will disable TLSv1](https://help.salesforce.com/apex/HTViewSolution?id=000221207).  

A surprising number of people are still using versions of Python before 2.7.9, which is the first version of Python 2 to support TLSv1.1.  This includes users of the most recent Ubuntu LTS, RHEL 7 and many other popular linux distros.  These users will need to have PyOpenSSL and friends installed (with a system openssl library >= 1.0.1) so that the requests library simple_salesforce uses can speak TLSv1.1.

Could you include documentation for these users to at least give them a pointer about where to go if they have this problem?  Are PRs on this topic welcome?

**Comment by cyndiec** [comment]
@calpaterson I've run into this issue, and not sure where to go from here. Any ideas?

`in SalesforceLogin
simple_salesforce.login.SalesforceAuthenticationFailed: UNSUPPORTED_CLIENT: TLS 1.0 has been disabled in this organization. Please use TLS 1.1 or higher when connecting to Salesforce using https.`

**Comment by calpaterson** [comment]
@cyndiec My understanding is that Salesforce as a whole hasn't disabled TLS 1.0 yet so your administrator might have changed a setting.  Perhaps you can persuade them to change it back!  Alternatively you can install the `requests[security]` package which will install and compile libraries that allow your system openssl to be used.  Hopefully your system openssl new enough to allow for TLSv1.1 (needs to be 1.0.1 or later)

@demianbrecht Ok.  When/if you can accept contributions again I'm happy to write this up.  Maybe my organisation has some other stuff we can contribute back too - I'll ask.

**Comment by cyndiec** [comment]
@calpaterson Our administrator ended up switching it back for now. Thank you so much for taking the time to explain this to me. I appreciate it.

**Comment by demianbrecht** [comment]
Ah yes, I'd forgotten about the `[security]` option for `requests` (I ended up installing `ndg-httpsclient` myself after debugging and finding that urllib3 uses it automatically if available). Thanks for pointing that out @calpaterson!

**Comment by demianbrecht** [comment]
@calpaterson we're good to accept contributions again, so if you have the bandwidth, a PR is most welcome!

**Comment by demianbrecht** [comment]
Should be resolved by #110 and available in v0.69.
