### ISSUE TITLE
How do I pass the salesforce API version? 

### ISSUE THREAD

**Issue by abhidotnet** [simple-salesforce/simple-salesforce#111]
I am trying to use following code and it throws an error.

`sf=Salesforce(username='user@myuser.com.sandbox1',password='mypassw0rds',security_token=None,sandbox=True,sf_version='30.0',proxies=None,session=None)`

This throws an error.

**`TypeError: __init__() got an unexpected keyword argument 'sf_version'`**

**Comment by demianbrecht** [comment]
Hi @abhidotnet, you want to use the `version` parameter, not `sf_version`.

**Comment by abhidotnet** [comment]
Thanks demianbrecht. 

_Unrelated, but I am having a tough time trying to have the correct code formatting on the wiki pages._
