### ISSUE TITLE
TLS on Python 3.4/3.5

### ISSUE THREAD

**Issue by NeRj** [simple-salesforce/simple-salesforce#117]
`File "/Users/waveoc1-3/PycharmProjects/ecommerce-core/env/lib/python3.4/site-packages/simple_salesforce/api.py", line 92, in __init__
    proxies=self.proxies)
  File "/Users/waveoc1-3/PycharmProjects/ecommerce-core/env/lib/python3.4/site-packages/simple_salesforce/login.py", line 135, in SalesforceLogin
    raise SalesforceAuthenticationFailed(except_code, except_msg)
simple_salesforce.login.SalesforceAuthenticationFailed: UNSUPPORTED_CLIENT: TLS 1.0 has been disabled in this organization. Please use TLS 1.1 or higher when connecting to Salesforce using https.`
Cannot connect to Salesforce with enabled TLS 1.1 with last version of simple-salesforce on Python 3.4/3.5 (OS X 10.11.5).

**Comment by jasonschroeder-sfdc** [comment]
Hi @NeRj - have you tested version 0.69? Looks like this was recently fixed in #103 . Cheers!

**Comment by NeRj** [comment]
@jasonschroeder-sfdc on Python 2.7 it works perfectly. But if I try login with username, password and organization ID on Python 3.5/3.5 then got an error:
`simple_salesforce.login.SalesforceAuthenticationFailed: INVALID_LOGIN: Invalid username, password, security token; or user locked out.`
If I pass to organization ID an empty string got error:
`simple_salesforce.login.SalesforceAuthenticationFailed: UNSUPPORTED_CLIENT: TLS 1.0 has been disabled in this organization. Please use TLS 1.1 or higher when connecting to Salesforce using https.`

**Comment by mattkatz** [comment]
I'm getting the same problem.  I'm using 0.69.

```
(py35) [~/Projects/salesforce] pip install simple-salesforce
Collecting simple-salesforce
  Using cached simple-salesforce-0.69.tar.gz
Collecting requests[security] (from simple-salesforce)
  Downloading requests-2.11.1-py2.py3-none-any.whl (514kB)
    100% |████████████████████████████████| 522kB 1.1MB/s
Collecting pyOpenSSL>=0.13; extra == "security" (from requests[security]->simple-salesforce)
  Using cached pyOpenSSL-16.0.0-py2.py3-none-any.whl
Collecting ndg-httpsclient; extra == "security" (from requests[security]->simple-salesforce)
  Using cached ndg_httpsclient-0.4.2.tar.gz
Collecting pyasn1; extra == "security" (from requests[security]->simple-salesforce)
  Using cached pyasn1-0.1.9-py2.py3-none-any.whl
Collecting cryptography>=1.3 (from pyOpenSSL>=0.13; extra == "security"->requests[security]->simple-salesforce)
  Downloading cryptography-1.4-cp35-cp35m-macosx_10_10_x86_64.whl (1.4MB)
    100% |████████████████████████████████| 1.4MB 564kB/s
Collecting six>=1.5.2 (from pyOpenSSL>=0.13; extra == "security"->requests[security]->simple-salesforce)
  Using cached six-1.10.0-py2.py3-none-any.whl
Collecting cffi>=1.4.1 (from cryptography>=1.3->pyOpenSSL>=0.13; extra == "security"->requests[security]->simple-salesforce)
  Downloading cffi-1.7.0-cp35-cp35m-macosx_10_10_x86_64.whl (154kB)
    100% |████████████████████████████████| 163kB 1.9MB/s
Requirement already satisfied (use --upgrade to upgrade): setuptools>=11.3 in ./py35/lib/python3.5/site-packages (from cryptography>=1.3->pyOpenSSL>=0.13; extra == "security"->requests[security]->simple-salesforce)
Collecting idna>=2.0 (from cryptography>=1.3->pyOpenSSL>=0.13; extra == "security"->requests[security]->simple-salesforce)
  Using cached idna-2.1-py2.py3-none-any.whl
Collecting pycparser (from cffi>=1.4.1->cryptography>=1.3->pyOpenSSL>=0.13; extra == "security"->requests[security]->simple-salesforce)
  Using cached pycparser-2.14.tar.gz
Building wheels for collected packages: simple-salesforce, ndg-httpsclient, pycparser
  Running setup.py bdist_wheel for simple-salesforce ... done
  Stored in directory: /Users/mk/Library/Caches/pip/wheels/86/00/4b/9529fd1cc853fbdd206a7c6f8411cfe67ccd345b0c1edb53d2
  Running setup.py bdist_wheel for ndg-httpsclient ... done
  Stored in directory: /Users/mk/Library/Caches/pip/wheels/44/6b/b1/eef816d523c0aa93f350fd2a78d74769e010e2f26623921b76
  Running setup.py bdist_wheel for pycparser ... done
  Stored in directory: /Users/mk/Library/Caches/pip/wheels/9b/f4/2e/d03e949a551719a1ffcb659f2c63d8444f4df12e994ce52112
Successfully built simple-salesforce ndg-httpsclient pycparser
Installing collected packages: pyasn1, pycparser, cffi, idna, six, cryptography, pyOpenSSL, ndg-httpsclient, requests, simple-salesforce
Successfully installed cffi-1.7.0 cryptography-1.4 idna-2.1 ndg-httpsclient-0.4.2 pyOpenSSL-16.0.0 pyasn1-0.1.9 pycparser-2.14 requests-2.11.1 simple-salesforce-0.69 six-1.10.0
```

I get the following error
```
(py35) [~/Projects/salesforce] cat log.txt
Traceback (most recent call last):
  File "clientbase-backup.py", line 7, in <module>
    sf = Salesforce(username=uname,password=pword, security_token=stoken, sandbox=True, instance=inst)
  File "/Users/mk/Projects/salesforce/py35/lib/python3.5/site-packages/simple_salesforce/api.py", line 92, in __init__
    proxies=self.proxies)
  File "/Users/mk/Projects/salesforce/py35/lib/python3.5/site-packages/simple_salesforce/login.py", line 135, in SalesforceLogin
    raise SalesforceAuthenticationFailed(except_code, except_msg)
simple_salesforce.login.SalesforceAuthenticationFailed: UNSUPPORTED_CLIENT: TLS 1.0 has been disabled in this organization. Please use TLS 1.1 or higher when connecting to Salesforce using https.
```

**Comment by mattkatz** [comment]
ok - more digging.  Looks like if you've got an [old version of OpenSSL installed, that gets used](https://comeroutewithme.com/2016/03/13/python-osx-openssl-issue/). 
Like post author, I had 
```
>>> print( ssl.OPENSSL_VERSION)
OpenSSL 0.9.8zh 14 Jan 2016
```
Which is no bueno - apparently getting to over v 1 is important. I haven't worked out how to upgrade my openssl yet, but that's what I'm going to try. 

Otherwise maybe passing an already open requests session is what I'll try...

**Comment by eagleDiego** [comment]
I get the same issue but only if I want to connect to sandbox:
`sf = Salesforce(username='user', password='pass', security_token='TheToken', sandbox=True)`

The same exact script with `sandbox=False` and the appropriate login details works:
`sf = Salesforce(username=fw_user, password=fw_pass, security_token=fw_token, sandbox=False)`

My version of OpenSSL is apparently also an old one:
```>>> print(ssl.OPENSSL_VERSION)
OpenSSL 0.9.8zh 14 Jan 2016```

Would it be possible that within the same organization Sandbox and Production have different security settings?

**Comment by demianbrecht** [comment]
First off, my apologies for being so late chiming in on this, I've been on a bit of a hiatus.

@mattkatz if you're using the requests[security] package, then it /should/ be using pyopenssl rather than the version of SSL that your version of Python was compiled with:

```
from OpenSSL import SSL
hex(SSL.OPENSSL_VERSION_NUMBER)
```

You can determine the OpenSSL version number using the details here: https://www.openssl.org/docs/manmaster/crypto/OPENSSL_VERSION_NUMBER.html

I've tried to repro the issues encountered between 2.7 and 3.5 and have been unable to so far (albeit it's a dev org without a sandbox). I'll try against a different org as soon as I can.

**Comment by renatoliveira** [comment]
Using Python 3.5.1, with simple salesforce 0.72, latest Homebrew and macOS, and I'm getting the same "TLS 1.0 has been disabled in this organization" error. 

I installed Python 3 using Homebrew, and OpenSSL is at 1.0.2, which as I understand is the last stable version.

Isn't there a way to force the use of TLS 1.1? 😭  I could really really use some Python power right now.

**Comment by tggagne** [comment]
So as of today on osx without opennsl libraries (removed by Apple) am I to understand there's no way to install simple-salesforce on the default Python 2.7 that comes with osx?
