### ISSUE TITLE
Expose API usage

### ISSUE THREAD

**Issue by cseager** [simple-salesforce/simple-salesforce#118]
The Salesforce API returns a usage report in the header of each response, as detailed in the documentation: https://developer.salesforce.com/docs/atlas.en-us.api_rest.meta/api_rest/headers_api_usage.htm
it looks something like `Sforce-Limit-Info: api-usage=18/5000`. 

It would be very helpful to be able to track our API usage, but it doesn't look like the simple-salesforce library exposes this information. I'd like to add a variable to instances of `Salesforce` objects that gets updated in `_call_salesforce()`, and potentially a similar variable in `SFType` objects that transfers to the `Salesforce` object in the `__getattr__` method. Are there any other methods I should account for in this change?

**Comment by Daenyth** [comment]
I'm going to be implementing a `Salesforce` subclass in a project soon that's going to handle rate limiting and other stuff - this behavior should be pretty easy, looking at the current code. When I get that done I'll PR in an addition. @demianbrecht would it be a reasonable implementation to return this information in the top level result dict?

**Comment by cseager** [comment]
@Daenyth if there's something about the open PR #119  that doesn't meet your needs, can you make a suggestion on there?

**Comment by Daenyth** [comment]
I didn't know it was there, I'll have a look.

**Comment by andscoop** [comment]
Closing - PR is merged and appears to resolve @Daenyth 's issue.
