### ISSUE TITLE
Assignment Rule Header - disable the default rule?

### ISSUE THREAD

**Issue by tarxvf** [simple-salesforce/simple-salesforce#120]
Thank you all for your hard work, great tool ..
 (this may not be a feature enhancement.. just me thinking too hard.. on a Friday..)

 I'm triggering a condition with my updates that cause the "owner" to change due to the [Default Assignment rule](https://developer.salesforce.com/docs/atlas.en-us.api_rest.meta/api_rest/headers_autoassign.htm) in SF. According to the [Restful API documentation](https://resources.docs.salesforce.com/sfdc/pdf/api_rest.pdf) one can pass a header to change this default behavior:

Sforce-Auto-Assign: FALSE

however in api.py:

    def _call_salesforce(self, method, url, **kwargs):
        """Utility method for performing HTTP call to Salesforce.

        Returns a 'requests.result' object.
        """
        headers = {
            'Content-Type': 'application/json',
            'Authorization': 'Bearer ' + self.session_id,
            'X-PrettyPrint': '1'
        }
        result = self.request.request(method, url, headers=headers, **kwargs)

am I missing an obvious way to append to the header or would it be beneficial to add a convention to include additional header items?

**Comment by crschilling** [comment]
Also running into a similar issue where I need to append additional header items (Set Assignment Rule Header and Set Email Header). Wondering if there is a solution or workaround.

Thanks!

**Comment by tarxvf** [comment]
yes, there is a related Pull Request available.. found it implemented by @nitzanm here [Allow custom HTTP headers when calling the update() method #104](https://github.com/simple-salesforce/simple-salesforce/pull/104) solves a myriad of issues.. and was exactly the direction I was thinking when I posted this issue initially.

**Comment by meilke** [comment]
Since there was no movement on #104, I created #131.

**Comment by demianbrecht** [comment]
This should be resolved by #131, which is now merged and will be in the next release on PyPI.
