### ISSUE TITLE
Query with Id IN array

### ISSUE THREAD

**Issue by tharrington** [simple-salesforce/simple-salesforce#137]
Is it possible to query where Id is in an array of Ids? For example:

```
myArray = ["1234", "1233"]
sf.query("SELECT Id, Email FROM Contact WHERE Id IN :" + myArray)
```

**Comment by demianbrecht** [comment]
[Here](https://developer.salesforce.com/docs/atlas.en-us.204.0.soql_sosl.meta/soql_sosl/sforce_api_calls_soql_select_filtering_polymorphic_relationships.htm)'s an example of using `IN` in a SOQL query.
