### ISSUE TITLE
restful() should handle non-200 success codes

### ISSUE THREAD

**Issue by demianbrecht** [simple-salesforce/simple-salesforce#146]
There are endpoints in the Salesforce API that result in non `200` response codes (i.e. 201 from [upserts](https://developer.salesforce.com/docs/atlas.en-us.api_rest.meta/api_rest/dome_upsert.htm)). Currently, `restful()` will result in an exception being raised if the response code is [not strictly `200`](https://github.com/simple-salesforce/simple-salesforce/blob/ef0a9487a6cd4854466d00969c32da000d34392a/simple_salesforce/api.py#L271). This should be updated to accept anything outside of obvious error code ranges (`4xx` and `5xx`).

**Comment by skamensky** [comment]
I have a fix for this. Do I need permission to push? Also, can I push through GitKraken?

**Comment by demianbrecht** [comment]
@skamensky thanks! The best way to contribute a patch is to fork this repo under you own account, push your changes there and then open a PR from there (you can do that through the Github UI). I'm not sure about GitKraken, but seems to me that it's just a UI layer on top of git so I don't see why you wouldn't be able to push to your own forked repo from it.

**Comment by skamensky** [comment]
Thank you! I've done my first commit.
