### ISSUE TITLE
update: HTTP Method 'PATCH' not allowed

### ISSUE THREAD

**Issue by iffy** [simple-salesforce/simple-salesforce#157]
I'm getting the following error when doing some updates:

```
  File "/var/www/app/lib/python3.5/site-packages/simple_salesforce/api.py", line 630, in update
    data=json.dumps(data), headers=headers
  File "/var/www/app/lib/python3.5/site-packages/simple_salesforce/api.py", line 711, in _call_salesforce
    _exception_handler(result, self.name)
  File "/var/www/app/lib/python3.5/site-packages/simple_salesforce/api.py", line 792, in _exception_handler
    raise exc_cls(result.url, result.status_code, name, response_content)
simple_salesforce.api.SalesforceGeneralError: Error Code 405. Response content: [{'message': "HTTP Method 'PATCH' not allowed. Allowed are HEAD,GET,POST", 'errorCode': 'METHOD_NOT_ALLOWED'}]
```

**Comment by superhero1** [comment]
> some updates
Can you please provide more information what you executed?

**Comment by iffy** [comment]
I think it happened when I did an update with no update data (e.g. `client.MyTable.update(identity, {})`)

**Comment by leonardoam** [comment]
Hey guys,

I got the same error (HTTP Method 'PATCH' not allowed) with upsert method today.
Do you have any clues about it?
Indeed, I tried making a manual curl to Salesforce using PATCH, and it looks like the endpoint for PATCH upsert must have the external id appended, not just the external id name.

Request is being currently made to https://{instance}/services/data/v{version}/record_id.
It should go to something like this: https://{instance}/services/data/v{version}/record_id/id.

I've made the changes in my fork and now it seems to work fine, I may be doing a PR with it tomorrow.
Hope you have something to add to my conclusions.

**Comment by erikhendrickson** [comment]
Was this ever resolved?

**Comment by iffy** [comment]
@erikhendrickson I don't remember but I do think it was from an empty update (`{}`).  I'm fine closing this as I don't know how to duplicate it and I don't need to fix it (what I'm doing works).
