### ISSUE TITLE
Add Bulk API functionality?

### ISSUE THREAD

**Issue by instructure-analytics** [simple-salesforce/simple-salesforce#158]
Are there any plans to add functionality for bulk api's into simple-salesforce?

**Comment by ddow** [comment]
https://github.com/simple-salesforce/simple-salesforce/pull/143

**Comment by Tecktron** [comment]
@instructure-analytics I'm in the same boat, waiting for the PRs to come though and get the updates though the next pypi update. In the meantime, I'm using the package [SalesforceBulkJob,](https://pypi.python.org/pypi/salesforce_bulk_api/1.2.0) which uses simple-salesforce on it's backend, in hopes that when this does come down the pipeline, it's an easy update for me. Hope that helps.
