### ISSUE TITLE
Uploading attachments

### ISSUE THREAD

**Issue by nicoknoll** [simple-salesforce/simple-salesforce#167]
Hey,
is it somehow possible to upload attachments as well via "simple-salesforce"?

Greets,
Nico

**Comment by wmetz-FPSS** [comment]
Thanks for your suggestion @skamensky ! Unfortunately I am still reciving the:
Maximum size of request reached. Maximum size of request is 52428800 bytes.', 'errorCode': 'JSON_PARSER_ERROR'}]

I am hesitant to write this off as a salesforce exception as they have some documentation of the ability to upload these objects via the REST API.

**Comment by skamensky** [comment]
You're posting about isssue https://github.com/simple-salesforce/simple-salesforce/issues/195.
In the [link ](https://developer.salesforce.com/docs/atlas.en-us.api_rest.meta/api_rest/dome_sobject_insert_update_blob.htm)you included, Salesforce explicitly gives you their limitation.

>You can insert or update blob data using a non-multipart message, but if you do, you are limited to 50 MB of text data or 37.5 MB of base64–encoded data.

**Comment by kev5** [comment]
@skamensky Hi, thanks for your answer. I had one question though, using your steps, all my files get pushed to the `Files` section in the client's Salesforce. What if I want each row in my .txt to be displayed in the `Opportunities` section? I changed the `'PathOnClient'` to `'Opportunities/'` but that didn't help.

**Comment by skamensky** [comment]
@kev5 , `PathOnClient` doesn't determine where in SF the file shows up.

According to the [documentation](https://developer.salesforce.com/docs/atlas.en-us.api.meta/api/sforce_api_objects_contentversion.htm) `PathOnClient` is the

>...complete path of the document. One of the fields that determines the FileType. Specify a complete path including the path extension in order for the document to be visible in the Preview tab.

If you want the files to show up in a specific place on the layout you need to add it explicitly. Depending whether you're using classic or lightning there are different ways of doing this. I'm afraid I can't help you with that.

**Comment by kev5** [comment]
@skamensky Thanks for getting back to me. I did check the docs but they are very vague and don't have any examples for me to understand :(

When you say 'you need to add explicitly', do you mean that there is no way to upload a file to a specific tab in the UI programmatically? I'm using lightning, can you provide a starter or a reference to a guide that can help me start? Thanks again

**Comment by skamensky** [comment]
@kev5 Sure.

https://success.salesforce.com/apex/answers?id=9063A000000DxAsQAK
https://trailhead.salesforce.com/en/content/learn/modules/lex_migration_customization/lex_migration_customization_layouts_ui

**Comment by yasersakkaf** [comment]
For uploading an image it worked for me 

'''
from simple_salesforce import Salesforce
import base64

sf = Salesforce(username='your_username', password='your_password', security_token='your_security_token')

# read the file in binary mode
f_path = 'your_image_path'
with open(f_path, 'rb') as f:
    file_data = f.read()

# salesforce content version data is base 64 encoded. Must be of str type to be json serializable. 
byte_string = str(base64.b64encode(file_data))

# Trim the leading b' and trailing apostrophe. 
byte_string = byte_string[2:-1]

fields = {'title' : 'image_name.jpg', 'PathOnClient' : f_path, 'VersionData' : byte_string}
cv = sf.ContentVersion.create(fields)
'''
