### ISSUE TITLE
Sandbox=False Required

### ISSUE THREAD

**Issue by afs2015** [simple-salesforce/simple-salesforce#169]
I was wondering if anyone else was running into this issue. To connect to my non-sandbox environments i'm being required to add sandbox=False to login via Salesforce().

**Comment by jravesloot** [comment]
I don't have that issue, with ver. 0.72.2.  Maybe post the version and the stacktrace?

**Comment by andscoop** [comment]
@afs2015 bump - please update if you are still experiencing the issue.

**Comment by afs2015** [comment]
@andscoop: Apologizes, missed the notification about this. I'll attempt this tomorrow and update this issue based on the result.

**Comment by afs2015** [comment]
Just tested it without sandbox=False and was about to connect to production fine. I'll close this issue.
