### ISSUE TITLE
Bulk query doesn't seem to be returning any data for the same query

### ISSUE THREAD

**Issue by bcjll** [simple-salesforce/simple-salesforce#176]
query = SELECT Id FROM Contact WHERE LastName = '<lastname>'
sf.query_all(query)
sf.bulk.Contact.query(query)

The 2nd call returns error below which is related to not having any results.
     url_query_results = "{}{}{}".format(url, '/', result.json()[0])
IndexError: list index out of range

**Comment by colemanja91** [comment]
I'll try to take a look this evening

**Comment by chachra** [comment]
Happening for me as well.

**Comment by andscoop** [comment]
Closing out in favor of #182 in order to consolidate decision making/ development on this issue.
