### ISSUE TITLE
SSL Error Bad Handshake

### ISSUE THREAD

**Issue by gokumatrix** [simple-salesforce/simple-salesforce#184]
I'm trying to do a basic query in my sandbox environment, but I can't seem to get through the login portion. 

Error:
`requests.exceptions.SSLError: HTTPSConnectionPool(host='login.salesforce.com', port=443): Max retries exceeded with url: /services/Soap/u/38.0 (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",),)`

SalesPass is my password, SalesUser is my username. orgID is the name of my organization, so I'm not sure if maybe I'm supposed to have a number in there that SF assigned to me. Am I missing something obvious here?

`sf = Salesforce(instance_url='<sandbox_URL>.my.salesforce.com/', sandbox=True, session_id='')`

`sf = Salesforce(password=str(SalesPass), username=str(SalesUser), organizationId='<orgID>', proxies=proxies)`

**Comment by demianbrecht** [comment]
@gokumatrix are you still experiencing issues with this? This seems likely to be something outside of the domain of the Salesforce client and rather with the SSL layer.

**Comment by andscoop** [comment]
@gokumatrix Bump. Please respond with any updated information and we can attempt to resolve this. Will close out in 15 days if no response.

**Comment by invertedfjord** [comment]
I am running into the same issue trying to do a very basic query

**Comment by andscoop** [comment]
@invertedfjord @gokumatrix 
https://stackoverflow.com/questions/10667960/python-requests-throwing-sslerror#12864892

This link may help you.

**Comment by bass-dee** [comment]
well I am getting this error messages lately. in the past it worked perfectly, now not anymore.
Moreover it says:

From cffi callback <function _verify_callback at 0x000000001DBF3BA8>:
Traceback (most recent call last):
  File "C:\Users\SuperErazer\Anaconda2\envs\gl-env\lib\site-packages\OpenSSL\SSL.py", line 313, in wrapper
    _lib.X509_up_ref(x509)
AttributeError: 'module' object has no attribute 'X509_up_ref'

Login, username and token are correct.
Did you or Salesforce introduced some changes, so that the  ssl certificate can’t get verified anymore?

I did following, but didnt help: 
pip uninstall -y certifi
pip install certifi==2015.04.28

Moreover I contacted my saleforce admin, maybe they know sth.

**Comment by H4kor** [comment]
Had a similar error after rebuilding my virtualenv. The error was caused by a newer version of pyOpenSSL (Version 17.5.0).

`pip install -U pyOpenSSL==17.3.0` fixed the issue.

**Comment by bass-dee** [comment]
thanks, yes, it is working now. I also figured out, that I coulnt call any APIs anymore, since the OpenSSL got updated 4 days ago, now it is fine.

**Comment by invertedfjord** [comment]
Thanks guys. @H4kor had the solution with the new version of Open SSL

**Comment by Ranjanpiyush** [comment]
i tried using the 17.3.0 version but still i am facing the SSL certificate error. Is it possible that this might be due to the settings of the firewall used by my organization? i am clueless how to resolve this issue, suddenly getting this since the past 2 days. Any help will be really appreciated.

**Comment by su347789** [comment]
I am also facing same issue and tried with all the solutions given above but did not work anything for me, any further help please..?

> ERROR - HTTPSConnectionPool(host='login.salesforce.com', port=443): Max retries exceeded with url: /services/Soap/u/38.0 (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",),))
> Traceback (most recent call last):
