### ISSUE TITLE
Login can raise ExpatError

### ISSUE THREAD

**Issue by Daenyth** [simple-salesforce/simple-salesforce#193]
Since there's a SalesforceError type and it's not documented that this can be raised, I assume it's unintentional. Can it be caught and wrapped appropriately?

```
  File "simple_salesforce/api.py", line 117, in __init__
    client_id=client_id)
  File "simple_salesforce/login.py", line 153, in SalesforceLogin
    response.content, 'sf:exceptionCode')
  File "simple_salesforce/util.py", line 16, in getUniqueElementValueFromXmlString
    xmlStringAsDom = xml.dom.minidom.parseString(xmlString)
  File "xml/dom/minidom.py", line 1928, in parseString
    return expatbuilder.parseString(string)
  File "xml/dom/expatbuilder.py", line 940, in parseString
    return builder.parseString(string)
  File "xml/dom/expatbuilder.py", line 223, in parseString
    parser.Parse(string, True)
```

`ExpatError('mismatched tag: line 9, column 6',)`

Using simple_salesforce 0.70

**Comment by skamensky** [comment]
How did you get this error? Can you post the code that got you this error?

**Comment by Daenyth** [comment]
It was `Salesforce(username=username, password=password, security_token=token)`, for some specific credentials. I'm pretty sure it was a transient error triggered by something that salesforce returned in error.

**Comment by skamensky** [comment]
Yes, this looks like an error that's not being caught. So far, it looks like the string `sf:exceptionCode` is not in the response either because Salesforce has changed their XML schema, or because you are running into an error simple-salesforce isn't aware of. 

Do you have any clue as to what could be causing this error? E.g. `LOGIN_DURING_RESTRICTED_DOMAIN` or `LOGIN_DURING_RESTRICTED_TIME`?
Also, what version of simple-salesforce and SF API are you using?

**Comment by skamensky** [comment]
Can you run this code and post the response content? That should help clarify the issue. Just plug in your username, password, and token when you run it.

```
try:
	# Python 3+
	from html import escape
except ImportError:
	from cgi import escape

from simple_salesforce import login
import requests

username = ''
password = ''
security_token = ''
domain = 'login'
sf_version = '36'

login_soap_request_body = """<?xml version="1.0" encoding="utf-8" ?>
        <env:Envelope
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:env="http://schemas.xmlsoap.org/soap/envelope/"
                xmlns:urn="urn:partner.soap.sforce.com">
            <env:Header>
                <urn:CallOptions>
                    <urn:client>{client_id}</urn:client>
                    <urn:defaultNamespace>sf</urn:defaultNamespace>
                </urn:CallOptions>
            </env:Header>
            <env:Body>
                <n1:login xmlns:n1="urn:partner.soap.sforce.com">
                    <n1:username>{username}</n1:username>
                    <n1:password>{password}{token}</n1:password>
                </n1:login>
            </env:Body>
        </env:Envelope>""".format(
            username=escape(username), password=escape(password), token=security_token,
            client_id=login.DEFAULT_CLIENT_ID_PREFIX)

login_soap_request_headers = {
	'content-type': 'text/xml',
	'charset': 'UTF-8',
	'SOAPAction': 'login'
}

soap_url = 'https://{domain}.salesforce.com/services/Soap/u/{sf_version}'.format(domain=domain, sf_version=sf_version)

response = requests.post(
	soap_url, login_soap_request_body, headers=login_soap_request_headers,
	)

print(str(response.content))

```

**Comment by Daenyth** [comment]
I don't think that will help - it does not fail reliably. Specifically it happened 4 times on one day and didn't happen again.

I think SF's api was having a problem on that day. The code works as of right now.

**Comment by andscoop** [comment]
@Daenyth Agree with @skamensky please open an issue and reference this issue if you are able to catch error in future.
