### ISSUE TITLE
No connected-app login support

### ISSUE THREAD

**Issue by AlmightyOatmeal** [simple-salesforce/simple-salesforce#194]
With having `client_id` available, I would have assumed there would have been support for logging in via connected-app credentials but there is no `client_secret` option.

**Comment by skamensky** [comment]
simple_salesforce supports providing your own instance url and session id as a method of authenticating.

`client_secret` is not a password and cannot be used by itself to authenticate. As [Salesforce documentation ](https://developer.salesforce.com/docs/atlas.en-us.api_rest.meta/api_rest/intro_understanding_user_agent_oauth_flow.htm)says

> These apps can protect per-user secrets. But, because the apps are widely distributed, the client secret can’t be confidential.

 You either need to set up full web server authentication flow with a redirect url, or if all you need to do is identify that you application is logging into Salesforce, you can use user-password flow with simple_salesforce which doesn't require any user interaction.

Like this:
```
import requests
from simple_salesforce import Salesforce

#should be https://login.salesforce.com/services/oauth2/token if you're not in a sandbox
url = 'https://test.salesforce.com/services/oauth2/token' 

#taken from https://developer.salesforce.com/docs/atlas.en-us.api_rest.meta/api_rest/intro_understanding_username_password_oauth_flow.htm
data = {'client_secret': 'yourclientsecrethere',
'client_id': 'yourcrazylongclientidhere',
'grant_type': 'password',
'username': 'yourusernamehere',
'password': 'yourusernamehere' + 'yourtokenhere'
}

response = requests.post(url,data=data).json()

#feed in your token and instance url here
sf = Salesforce(instance_url=response['instance_url'],session_id=response['access_token'])
```

Maybe login.py should do most of this for you...

**Comment by andscoop** [comment]
@AlmightyOatmeal Leaving open for 15 days in order to allow time for you to expand on your request or verify that your question was resolved.

**Comment by thunder2k** [comment]
Hi,
sorry for resurrecting this old issue but it seems I'm facing the same problem.

What I think the OP was trying to say is that there's no way to authenticate via connected app without dealing with token request/parsing response.

It would be great to be able to provide your connected app key and secret, together with username and password and to directly login this way.

Example:
`client = Salesforce(username='username',
                    password='password',
                    client_id='YOUR_CLIENT_ID',
                    client_secret='YOUR_CLIENT_SECRET',
                    is_sandbox=True)`

Please let me know if there's an alternative to achieve this.

Thanks!

Bye
