### ISSUE TITLE
Bad Request when attempting to insert a ContentVersion (File)

### ISSUE THREAD

**Issue by wmetz-FPSS** [simple-salesforce/simple-salesforce#195]
I am receiving the following error when attempting to insert a ContentVersion File of < .5 GB 

Maximum size of request reached. Maximum size of request is 52428800 bytes.', 'errorCode': 'JSON_PARSER_ERROR'}]

Can simple-salesforce handle this type of upload?

**Comment by skamensky** [comment]
Looks like a Salesforce API limitation.
https://help.salesforce.com/articleView?id=000002608&type=1
'When attempting to Import Attachments or Content you may receive an error stating: "Maximum size of request reached.  Maximum size of request is 52428800 bytes."'

**Comment by wmetz-FPSS** [comment]
Does that mean the maximum file size? Or the size of the request? 

Does this maybe need to be done outside of Simple-Salesforce with the python requests library? 

From assembly seems to have found a way to do this here: https://www.formassembly.com/blog/upload-salesforce-files/

**Comment by skamensky** [comment]
I don't think using the requests library will help you. Simple-Salesforce uses the requests library behind the scenes to post and get data. 

I don't know how Form Assembly is doing their insertions. They can't be using the REST API, which is what Simple-Salesforce is using, if they have gotten around it. As far as I know, the only way to upload content larger than 50mb is through Javascript in Visualforce. I think in order to do that your code needs to be executing on Salesforce's servers due to cross-site scripting protection.

Have you considered alternative content storage solution aside from Salesforce (e.g. Box.com has a good integration)?

**Comment by wmetz-FPSS** [comment]
It seems Form Assembly has a hard limit on 25MB per form upload. That is likely why they are able to do it. I appreciate your help and patience. We're currently looking into a third party solution to act as our file repo.

**Comment by skamensky** [comment]
Yes, we've done that at our company as well. Salesforce content can be difficult to work with depending on your use case.

**Comment by andscoop** [comment]
Closing out as it is an API Limitation

**Comment by aburzyn** [comment]
Hi everyone, we came across this issue recently in some automation tasks we maintain (simple-salesforce==0.75.3, python 2). We managed  to get a workaround  the following way:

```
def create_version_large_file(sf, filename, title=None):
    """This implementation allows uploads of files which size is larger than 50MB

        Args:
        sf (Salesforce): simple_salesforce.Salesforce instance
        filename (string): Filename (in this impl has to be in current directory)
        title (string, optional): Title for Salesforce
    """
    if title is None:
        title = filename

    url = '{}sobjects/ContentVersion'.format(sf.base_url)

    metadata = json.dumps({
        'Title': title,
        'PathOnClient': filename,
    })

    with open(filename, 'rb') as f:
        content = f.read()

    files = [
        ('entity_content', ('', metadata, 'application/json')),
        ('VersionData', (filename, content, 'application/octet-stream'))
    ]

    headers = {
        'Authorization': sf.headers['Authorization'],
    }

    response = sf.session.post(url=url, headers=headers, files=files)
    json_response = response.json()

    version_id = json_response['id']
    return version_id
```
Basically, it reuses the simple_salesforce authentication and then creates the correct multipart request.
