### ISSUE TITLE
Support for Bulk Query PK Chunking w/ Foundation for Batches

### ISSUE THREAD

**Issue by andscoop** [simple-salesforce/simple-salesforce#200]
I would like to propose support for PK Chunking with the foundations of code that would support submitting multiple batches to a single job. This code change allows a user to stream a query to line delimited JSON in order to keep a lower memory footprint on large datasets.

PK Chunking
https://developer.salesforce.com/docs/atlas.en-us.api_asynch.meta/api_asynch/asynch_api_code_curl_walkthrough_pk_chunking.htm#!

Branch
https://github.com/astronomerio/simple-salesforce/tree/implement-bulk-query-streaming

**Comment by jon-wobken** [comment]
@andscoop -batch support added in v1.10 from pr #392
