### ISSUE TITLE
want to download a image file from database link in salesforce

### ISSUE THREAD

**Issue by bmabir17** [simple-salesforce/simple-salesforce#201]
i want to download an image file that is being stored in salesforce server. And it link has been stored in the database object as a record. 
This is the image link:
https://taroworks-1869--c.ap5.content.force.com/servlet/servlet.FileDownload?file=00P7F0000019706UAA

I have tried following code.
`
from PIL import Image
from simple_salesforce import Salesforce
import requests
import base64
import json
url = 'https://taroworks-1869.cloudforce.com/servlet/servlet.FileDownload?file=00P7F0000019706UAA'
sf = Salesforce(username=    #my Username
                ,password=   #my Password
                ,security_token= #token )

print ("get sid ", sf.session_id)
sid=sf.session_id
response = requests.get(url,
                  headers = sf.headers, cookies = {'sid' : sid})

response.contents`

But the error says,
Too many redirect, max redirect exceeded

**Comment by skamensky** [comment]
This is just a quick hack I came up with since 'sf.restful' was throwing a json decoding error.

```
#put your document id here
doc_id = '015i000000FCXF7'
doc_name = sf.Document.get(doc_id)['Name']
url = 'sobjects/Document/{doc_id}/body'.format(doc_id=doc_id)
#stream allows for the request to be retrieved incrementally in raw bytes
result = sf.session.get(sf.base_url+url,headers=sf.headers,stream=True)

with open(doc_name,'wb+') as file:
	#retrieve the bytes from the resources incrementally 
	for chunk in result.iter_content(1000):
		file.write(chunk)
```

**Comment by bmabir17** [comment]
I think i was not able to describe my problem properly. The following picture show a single record of a custom object. 
![screenshot-2017-12-10 child -000251 salesforce](https://user-images.githubusercontent.com/5344072/33803699-09097528-ddc0-11e7-9d24-ac0f1e6d7f30.png)

The image link named field is the one holding the image that i want to download using python.

@skamensky your code does not save anything in the doc_name file , it shows a empty image file

**Comment by skamensky** [comment]
Ah sorry, my code was for the document object. You're trying to access the attachment object. You just need to modify the url and the object you're getting the name from. Here's the new code.

```
#put your document id here
doc_id = '00Pi000000rhPSqEAM'
doc_name = sf.Attachment.get(doc_id)['Name']
url = 'sobjects/Attachment/{doc_id}/body'.format(doc_id=doc_id)
#stream allows for the request to be retrieved incrementally in raw bytes
result = sf.session.get(sf.base_url+url,headers=sf.headers,stream=True)

with open(doc_name,'wb+') as file:
	#retrieve the bytes from the resources incrementally 
	for chunk in result.iter_content(1000):
		file.write(chunk)
```

**Comment by andscoop** [comment]
@skamensky thanks for our time on this!

@bmabir17 Feel free to re-open if this is still an issue or if you have more questions

**Comment by brno32** [comment]
Does this approach handle the base64 decoding automatically?

**Comment by motcapbovit** [comment]
> Ah sorry, my code was for the document object. You're trying to access the attachment object. You just need to modify the url and the object you're getting the name from. Here's the new code.
> 
> ```
> #put your document id here
> doc_id = '00Pi000000rhPSqEAM'
> doc_name = sf.Attachment.get(doc_id)['Name']
> url = 'sobjects/Attachment/{doc_id}/body'.format(doc_id=doc_id)
> #stream allows for the request to be retrieved incrementally in raw bytes
> result = sf.session.get(sf.base_url+url,headers=sf.headers,stream=True)
> 
> with open(doc_name,'wb+') as file:
> 	#retrieve the bytes from the resources incrementally 
> 	for chunk in result.iter_content(1000):
> 		file.write(chunk)
> ```

This really help, thanks a lot
