### ISSUE TITLE
parent-child objects returned as ordered dicts within ordered dicts

### ISSUE THREAD

**Issue by mwolfe07** [simple-salesforce/simple-salesforce#203]
I'm trying to use the query_all function to pull out records and manipulate in a pd.DataFrame. Any reason nested objects, are returned by another ordered dictionary?

when doing a normal soql query of 

> "select id, account.id from opportunity limit 10"

It is returned as an ordered dict, which then in the results, also has another ordered dict within it for the account fields which is the parent-child object. 

I'm having a hard time getting this into a tabular dataframe for normal data manipulation. any help would be greatly appreciated!

**Comment by surfmaverick** [comment]
Here is an example of how you can make it work:

cf = sf.query_all("SELECT Instruments__c, Instruments__r.Common_Name__c, Instruments__r.Name__c,Date__c, Total_Payment__c, Interest_Due__c, Principal_Due__c, Payday__c, Payment_Number__c FROM Amort_Schedules__c WHERE Active__c = TRUE")


# In[ ]:

#run query on ALM ids
ALMs = sf.query_all("SELECT ID, Name From Obligations__C")


# In[ ]:

#confirm the length/dimension of the records extract
len(ALMs['records']), len(cf['records'])


# In[ ]:

ALMs = ALMs['records']


# In[ ]:

ALMs[1]


# In[ ]:

#to iterate through the keys in data
#for key in ALMs:
#   print(key['Id'], key['Name'])


# In[ ]:

#cf['records']


# In[ ]:

dfInstr = pd.DataFrame.from_dict(ALMs)


# In[ ]:

**dfCF = pd.DataFrame.from_dict(cf['records'])**


# In[ ]:

dfCF['date']=pd.to_datetime(dfCF['Date__c'])

**Comment by andscoop** [comment]
@mwolfe07 Feel free to re-open if issue is still or if you have more questions
