### ISSUE TITLE
Not an issue but a question, Is there a way to get a list of all the salesforce objects within a salesforce account. 

### ISSUE THREAD

**Issue by OtisHarrison24** [simple-salesforce/simple-salesforce#204]
Not an issue but a question, Is there a way to get a list of all the salesforce objects within a salesforce account. I was wanting to just create a list of all the salesforce object within my account.

**Comment by keg** [comment]
@OtisHarrison24 Not sure if you got what you were looking for but I did a variation of using the Metadata API described here: https://github.com/simple-salesforce/simple-salesforce#other-options
