### ISSUE TITLE
Pull Request test

### ISSUE THREAD

**Issue by mbr84** [simple-salesforce/simple-salesforce#212]
Hey all, I'm having a pull request blocked by a linter error in file I'm not working on, api.py. 
```R:424, 4: Either all return statements in a function should return an expression, or none of them should. (inconsistent-return-statements)```
The error is on line 424, and when I look it up, it seems to have been identified as a bug and removed from pylint. Any guidance what I should do to move forward?

**Comment by andscoop** [comment]
Looking at the git blame linked below it appears that trying to get fancy and return directly from `.json()` and `.text` in the method/attr resulted in this pylint error. I am not entirely sure why I was able to pass build test though. Either way,  I guess if I broke it I'm going to have to buy it. I will put a fix out shortly, which should resolve your issues.

https://github.com/simple-salesforce/simple-salesforce/blame/master/simple_salesforce/api.py#L424

**Comment by mbr84** [comment]
That fixed it. hooray!
