### ISSUE TITLE
Is it possible to download attachments?

### ISSUE THREAD

**Issue by TheWingineer** [simple-salesforce/simple-salesforce#218]
When attempting to run the following line, I get an error stating that utf8 codec can't decode byte 0xff in position 0:

attachment = sf.query_more(attachmentUrl + '/Body', True)

Is there another way to download attachments? Most of the attachments I'm expecting will be image and tar files.

**Comment by skamensky** [comment]
Did you check out this question?

https://github.com/simple-salesforce/simple-salesforce/issues/201

**Comment by TheWingineer** [comment]
You're my hero. Thanks mucho.

**Comment by skamensky** [comment]
No problem. Glad it worked out!
