### ISSUE TITLE
Salesforce certificates change from Symantec to DigiCert - impacts?

### ISSUE THREAD

**Issue by pbacken** [simple-salesforce/simple-salesforce#219]
Will this change impact simple-salesforce?

**Comment by andscoop** [comment]
https://help.salesforce.com/articleView?id=000269027&language=en_US&type=1
For reference

There are testing instructions here as well as rollout progress. 

But in general the SSL handshake should be handled by python `requests` library.

**Comment by andscoop** [comment]
We can reopen this if a more specific error actually occurs, but ty for the foresight on this one.
