### ISSUE TITLE
Upsert with external_id value containing "/" (forward slash) fails

### ISSUE THREAD

**Issue by jsullivanlive** [simple-salesforce/simple-salesforce#22]
I have a key field that is a url which fails on upsert because of the multiple forward slashes.  Upserts in salesforce are done by url, replacing the id after the resource name, so the forward slashes break the url.

To reproduce the error:

```
Salesforce().Account.upsert("myfield__c/http://mysite.com/id", {})
```

**Comment by candlerb** [comment]
Just to be clear, did you try this?

~~~
Salesforce().Account.upsert("myfield__c/http:%2F%2Fmysite.com%2Fid", {})
~~~

requests *should* leave the %2F's unchanged (this is a "reserved" character in RFC 2396).  Does it not?  If so, I can argue strongly that's a bug in requests.

Unfortunately, period is in the set of unreserved characters, so period and %2E are equivalent. RFC 2396 continues:

> Unreserved characters can be escaped without changing the semantics of the URI, but this **should not be done** unless the URI is being used in a context that does not allow the unescaped character to appear.

(my emphasis).  So if Salesforce really requires %2E, that's a Salesforce bug.
