### ISSUE TITLE
Bulk upsert example incorrect

### ISSUE THREAD

**Issue by tayloramurphy** [simple-salesforce/simple-salesforce#232]
In the Readme, the bulk upsert data example is as follows:

```python
data = [
  {'Id': '0000000000AAAAA', 'Email': 'examplenew2@example.com'},
  {'Id': '', 'Email': 'foo@foo.com'}
]
```
based on my testing and usage of this query, dictionaries that had `'Id': ''` were not actually inserted. Only by removing the `Id` key was I able to get it to work. 

I'm happy to make the PR to update this unless there's something I'm missing.

**Comment by gredondogc** [comment]
I've had the same problem on version 0.74.2. The inital page documentation still has the incorrect information.
