### ISSUE TITLE
Org62 no more access

### ISSUE THREAD

**Issue by jfrancoisbea** [simple-salesforce/simple-salesforce#236]
We now have error when trying to get a connection with Org62 !!!

**Comment by andscoop** [comment]
@jfrancoisbea What branch are you working off of? Could you please provide an output of the error?

**Comment by demianbrecht** [comment]
@jfrancoisbea are you a salesforce employee? If so, please reach out to me internally.

**Comment by jfrancoisbea** [comment]
In fact it's a Salesforce Issue on internal org Org62. We don't have any
more access by API. It was in case, but you're not Salesforce employee !

simple_salesforce.exceptions.SalesforceAuthenticationFailed: INVALID_LOGIN:
Invalid username, password, security token; or user locked out.


________________________________________________
Jean FRANCOIS

Program Architect | *in <https://www.linkedin.com/pub/JeanFrancoisBea>* |
salesforce.com <http://www.salesforce.com/signature>
Office:  +33 1 72 10 94 00
Mobile: +33 6 12 35 68 85

<http://www.salesforce.com/signature>

--

**Comment by demianbrecht** [comment]
@jfrancoisbea I am a Salesforce employee, which is why I requested that you contact me directly: dbrecht@salesforce.com.

**Comment by demianbrecht** [comment]
Closing as it's been taken offline. @jfrancoisbea please feel free to reopen if your problem isn't resolved and you think it's an issue with the library.
