### ISSUE TITLE
Unit Testing with simple-salesforce?

### ISSUE THREAD

**Issue by philchristensen** [simple-salesforce/simple-salesforce#239]
Hi folks. Thanks for the great library. I'm wondering if there's any suggestions or documentation around how to write unit tests for an application that uses simple_salesforce without making actual network connections.

**Comment by tedmiston** [comment]
@philchristensen Would Python's built-in [mock](https://docs.python.org/3/library/unittest.mock.html) work for you use case?  Another useful option is [requests-mock](https://github.com/jamielennox/requests-mock).

**Comment by philchristensen** [comment]
Ah, I think requests-mock was exactly what I needed. Thanks!

**Comment by demianbrecht** [comment]
FWIW, I've used [responses](https://github.com/getsentry/responses) almost religiously for projects based on requests and haven't run into memorable issues yet.
