### ISSUE TITLE
requests timeouts

### ISSUE THREAD

**Issue by lewy87r** [simple-salesforce/simple-salesforce#240]
Hey guys, how about timeouts? Sometimes my API hook waits forever for a response :)

requests don't have default timeout's and it should be implemented with send action, good to have it with init.

**Comment by andscoop** [comment]
@lewy87r You can [pass a custom requests session object](https://github.com/simple-salesforce/simple-salesforce/blob/master/simple_salesforce/api.py#L94
) with a timeout. [Here is an example](http://docs.python-requests.org/en/master/user/advanced/#prepared-requests) of specifying a timeout on a session
