### ISSUE TITLE
simple-salesforce removed from PyPI?

### ISSUE THREAD

**Issue by timchurch** [simple-salesforce/simple-salesforce#245]
It appears that simple-salesforce package was recently removed from PyPI.  Please re-publish this package so it can be installed using pip.

The following gives a 404 error page:
https://pypi.python.org/pypi/simple-salesforce

**Comment by demianbrecht** [comment]
Hey @timchurch, this may be an effect of [pypa](https://github.com/pypa)'s cutting over to the pypi.org beta. The package is still available at https://pypi.python.org/simple/simple-salesforce/, https://pypi.org/pypi/simple-salesforce/ and https://pypi.org/simple/simple-salesforce/ as well as through admin. Might be worthwhile touching base with them on IRC if you have the time to see if something's up.

**Comment by timchurch** [comment]
Thanks @demianbrecht.  Those links do work for me.  

However, I still see 0.73.0 as the latest version.  In Google search results yesterday, I saw 0.74.0 which appeared to have been uploaded recently.  What is the latest version that should be available?

Google cache - https://webcache.googleusercontent.com/search?q=cache:qQGVs_TWNnkJ:https://pypi.python.org/pypi/simple-salesforce/0.74.0+&cd=2&hl=en&ct=clnk&gl=us&client=firefox-b-ab

**Comment by demianbrecht** [comment]
Ah thanks Google. I believe there was a release and rollback. @nickcatal @tedmiston can you please confirm that?

**Comment by tedmiston** [comment]
Good catch, thank you!

That's correct that we rolled back the bad 0.74.0 release — we need to revisit why it broke.

I'm seeing on PyPI that every simple-salesforce release is set to hide=yes.  PyPI for this package is set to auto hide old releases when a new release comes out, so I'm thinking what happened is that when the new release was rolled back, it didn't unhide the previous latest release.  I've fixed that just now.

(Note that this only affects the web view not pip installs.)

@timchurch Can you confirm you see it again?

**Comment by timchurch** [comment]
Thanks all.  Everything looks fine now. 

Looking forward to the updated release including https://github.com/simple-salesforce/simple-salesforce/pull/223

**Comment by tedmiston** [comment]
Hey @timchurch, we pushed the updated 0.74.1 release out to PyPI late Friday night with a quick follow up release 0.74.2 that fixed the rst formatting issue in the readme as well.

Reference - https://github.com/simple-salesforce/simple-salesforce/issues/249
