### ISSUE TITLE
Invalid login issue

### ISSUE THREAD

**Issue by Daram** [simple-salesforce/simple-salesforce#260]
What I want to do is basically scrape a report from Salesforce but at first I have an issue with correctly logging into simplesalesforce API. My instance doesn't use security token, just single-sign on method (that's what I've been told from SFDC support) so I was trying to connect using organizationID.

from simple_salesforce import Salesforce

`sf = Salesforce(username='xxxx', password='yyyy', organizationId='zzzz')`

I've also tried multiple combinations with e.g. blank security token and/or organization id but I stil have the same error.
I noticed this is quite common issue but not one of the solutions I found on web worked for me.

 ```
File "scripty.py", line 3, in <module>
    sf = Salesforce(username='xxxx', password='yyyy', organizationId='zzzz')
  File "C:\Users\wwww\AppData\Local\Programs\Python\Python36\lib\site-packages\simple_salesforce\api.py", line 173, in __init__
    domain=self.domain)
  File "C:\Users\wwww\AppData\Local\Programs\Python\Python36\lib\site-packages\simple_salesforce\login.py", line 175, in SalesforceLogin
    raise SalesforceAuthenticationFailed(except_code, except_msg)
simple_salesforce.exceptions.SalesforceAuthenticationFailed: INVALID_LOGIN: Invalid username, password, security token; or user locked out.
```
That said, I am no python nor sfdc expert so I will be glad for any information. 
Thanks!

**Comment by jonfulk** [comment]
According to the other issue where this is already reported (https://github.com/simple-salesforce/simple-salesforce/issues/171), there was success by passing in `security_token=''`.

**Comment by andscoop** [comment]
@Daram Passing the security token should resolve your issue. Please re-open if this is not the case.
