### ISSUE TITLE
INVALID_SESSION_ID when Calling REST API Methods

### ISSUE THREAD

**Issue by vahedq** [simple-salesforce/simple-salesforce#272]
I have set session duration to 24 hours in security settings on Salesforce, but we are often getting `INVALID_SESSION_ID` when trying to call `sf.Lead.create()` or other methods. We are using user/password/security token to authenticate.

Any help is appreciated.

**Comment by andscoop** [comment]
@vahedq Can you share some example code you are using to authenticate, please hide any sensitive information, but leave the instance URL.

Also please share the full error message/ stack trace you are receiving.

**Comment by vahedq** [comment]
@andscoop thanks. this is the complete error we get:
`
Malformed request https://na57.salesforce.com/services/async/38.0/job. Response content: {u'exceptionMessage': u'Invalid session id', u'exceptionCode': u'InvalidSessionId'}
`

This is the code we have for authentication:
```
  from simple_salesforce import Salesforce

   salesforce = Salesforce(
      username=username,
      password=password,
      security_token=security_token
    )
```
;

And this fails (normally after a few ours of working fine)
`salesforce.Lead.create(payload)`.

By the way, the code runs on multiple servers with different IPs -- if that helps setting creating things in salesforce security dashboard.

**Comment by vahedq** [comment]
FWIW, this is what we ended up doing to solve the issue. Though, it triggers the initialization at very arbitrary time gaps and uses more API calls.

```
 salesforce = Salesforce(username=username, password=password, security_token=security_token)
 try:
      salesforce.Lead.create(...)
 except:
      if error == INVALID_SESSION_ID:
            salesforce = Salesforce(username=username ...)
            salesforce.Lead.create(.....)
      else:
          # log some other error.
```

**Comment by xmedeko** [comment]
Note, see also #292
