### ISSUE TITLE
How to set up Salesforce.query()  to use salesforce Bulk API

### ISSUE THREAD

**Issue by feichen008** [simple-salesforce/simple-salesforce#274]
Hi, Could you please share how to set up Salesforce.query()  to use salesforce Bulk API?  and how to set up the batchsize= 10000? 

sf = Salesforce(instance=instance, session_id=session_id)
SOQL= 'SELECR Id FROM Account'
qryResult = sf.query(query=SOQL) 

Thanks a lot!

**Comment by Totorokrut** [comment]
Hi,

Here you can find a couple of examples: https://stackoverflow.com/questions/43286524/how-can-one-make-salesforce-bulk-api-calls-via-simple-salesforce
