### ISSUE TITLE
sObject is not supported error in query - why?

### ISSUE THREAD

**Issue by elsigh** [simple-salesforce/simple-salesforce#287]
I'm trying to run a query that should just return an id so I think my lack of understanding about the internals has me confused by this message.

```
repository_id = sf1.query(
    "SELECT Id FROM ContentHubRepository WHERE Type='contentHubQuip' LIMIT 1")
```

Error is:
```
simple_salesforce.api.SalesforceGeneralError: [ {
  "message" : "sObject type 'ContentHubRepository' is not supported.",
  "errorCode" : "INVALID_TYPE"
}
```

I'm not sure why the library needs to understand a schema in order to execute a SQL query. Is there any way to execute a raw query perhaps? Advice on moving forward? This query does work in the Dev Console. 

Thanks for the cool library!

**Comment by cbohlman** [comment]
Are you running as a system admin?

**Comment by elsigh** [comment]
I'm afraid I don't understand the question. I'm running a python script locally against a salesforce instance. In the Dev Console, with the same credentials, I can execute the query from Query Builder.

**Comment by cbohlman** [comment]
Sorry I should have phrased that differently. I was asking if the running user's credentials were system admins. Better question would be to ask if the running user's credentials have read access to the ContentHubRepository object. Typically this error is returned from the API call if the user does not have read access to this object.

I'd suggest checking the object security settings for the user's profile, I just ran your code and didn't get this error

**Comment by andscoop** [comment]
@elsigh Were you able to get this working with the above advice?

**Comment by thommor** [comment]
Has this issue been resolved?

**Comment by elsigh** [comment]
This is a pretty out of date issue. I'm not sure how I resolved it anymore.

**Comment by thommor** [comment]
I know I'm going through all the old issues at the minute.

Thanks for the response

**Comment by daraul** [comment]
I got this error when attempting to query for trace flags. Below is my python.

```python
sf_data = pd.DataFrame(
    pd.json_normalize(
        sf.query_all(
            format_soql("SELECT Id, LogType, DebugLevelId, StartDate, ExpirationDate FROM TraceFlag WHERE TracedEntityId = {traced_entity_id} LIMIT 1",
                        traced_entity_id=traced_entity_id), include_deleted=False)['records']))
```

That throwss this:

```python
simple_salesforce.exceptions.SalesforceMalformedRequest: Malformed request https://xxx/services/data/v59.0/query/?q=SELECT+Id%2C+LogType%2C+DebugLevelId%2C+StartDate%2C+ExpirationDate+FROM+TraceFlag+WHERE+TracedEntityId+%3D+%27005Hs00000BmSXdIAN%27+LIMIT+1. Response content: [{'message': "sObject type 'TraceFlag' is not supported.", 'errorCode': 'INVALID_TYPE'}]
```

However, the exact same query works just fine from the CLI, *without* the tooling API flag:

```bash
sf data query -t --query "SELECT Id, LogType, DebugLevelId, StartDate, ExpirationDate FROM TraceFlag WHERE TracedEntityId = 'xxx'" -o yyy
```

**Comment by cbohlman** [comment]
> I got this error when attempting to query for trace flags. Below is my python.
> 
> sf_data = pd.DataFrame(
>     pd.json_normalize(
>         sf.query_all(
>             format_soql("SELECT Id, LogType, DebugLevelId, StartDate, ExpirationDate FROM TraceFlag WHERE TracedEntityId = {traced_entity_id} LIMIT 1",
>                         traced_entity_id=traced_entity_id), include_deleted=False)['records']))
> That throwss this:
> 
> simple_salesforce.exceptions.SalesforceMalformedRequest: Malformed request https://xxx/services/data/v59.0/query/?q=SELECT+Id%2C+LogType%2C+DebugLevelId%2C+StartDate%2C+ExpirationDate+FROM+TraceFlag+WHERE+TracedEntityId+%3D+%27005Hs00000BmSXdIAN%27+LIMIT+1. Response content: [{'message': "sObject type 'TraceFlag' is not supported.", 'errorCode': 'INVALID_TYPE'}]
> However, the exact same query works just fine from the CLI, _without_ the tooling API flag:
> 
> sf data query -t --query "SELECT Id, LogType, DebugLevelId, StartDate, ExpirationDate FROM TraceFlag WHERE TracedEntityId = 'xxx'" -o yyy

Check your CLI input, the `-t` flag enables the tooling API. Running the query without that arg returns the same error as your simple_salesforce call for me :)

**Comment by daraul** [comment]
I just noticed! I was able to work around it with the python below. Please ignore me 🙃 

```
 records = sf.toolingexecute(f"query?q=SELECT+Id,+LogType,+DebugLevelId,+StartDate,+ExpirationDate+FROM+TraceFlag+WHERE+TracedEntityId+=+'{traced_entity_id}'+LIMIT+1")
```
