### ISSUE TITLE
JunctionIdList?

### ISSUE THREAD

**Issue by andmer** [simple-salesforce/simple-salesforce#289]
Hi, thank you in advance.
I'm trying to create a message with a JunctionIDList parameter any ideas on  how to get it working?

sf.EmailMessage.create(
    {'FromAddress': 'foo@example.com',
     'ToAddress': 'bar@example.com',
     'Subject': 'MERMEGAS23',
     'TextBody': 'lorem ipsum dolor sit amet',
     'Status': 2,
     'BccIds': '003q000000wG1tLAAS'
     })

https://developer.salesforce.com/docs/atlas.en-us.object_reference.meta/object_reference/sforce_api_objects_emailmessage.htm

getting response:
simple_salesforce.exceptions.SalesforceMalformedRequest: Malformed request https://s21.my.salesforce.com/services/data/v38.0/sobjects/EmailMessage/. Response content: [{'message': 'Cannot deserialize instance of <unknown> from VALUE_STRING value 003q000000wG1tLAAS or request may be missing a required field at [line:1, column:146]', 'errorCode': 'JSON_PARSER_ERROR'}]

**Comment by andscoop** [comment]
Thank you for following up - I will close this issue, please re-open if you have any further questions.
