### ISSUE TITLE
Bulk Query returns DateTime values as integers

### ISSUE THREAD

**Issue by davidmreed** [simple-salesforce/simple-salesforce#290]
Given a connection:

    connection = Salesforce(
          instance_url=os.environ['INSTANCE_URL'],
          session_id=os.environ['ACCESS_TOKEN']
     )

executing a Bulk API query that includes DateTime fields returns integer values of unclear meaning rather than the expected ISO-format string.

    connection.bulk.Account.query('SELECT Name, CreatedDate, LastModifiedDate, SystemModStamp FROM Account')

> [{'CreatedDate': 1546659665000, 'SystemModstamp': 1546659665000, 'attributes': {'url': '/services/data/v38.0/sobjects/Account/0010R00000VsXkHQAV','type': 'Account'}, 'Name': 'ACME', 'LastModifiedDate': 1546659665000}, ... ]

Performing the same query with the REST API yields correct results:

> [OrderedDict([('attributes', OrderedDict([('type', 'Account'), ('url', '/services/data/v38.0/sobjects/Account/0010R00000VsXkHQAV')])), ('Name', 'ACME'), ('CreatedDate', '2019-01-05T03:41:05.000+0000'), ...

Changing the API version from 38.0 to 44.0 does not affect the behavior.

I'm using simple_salesforce-0.74.2, Python 3.5.2, and Ubuntu 16.04.

**Comment by davejagoda** [comment]
That 'integer value of unclear meaning' is the number of milliseconds since January 1st 1970:

```python -c "import datetime; print(datetime.datetime.isoformat(datetime.datetime.fromtimestamp(1546659665000/1000)))"
2019-01-04T19:41:05
```

Seems like a bug that it returns different date formats depending on the type of query.

**Comment by davidmreed** [comment]
Further experimentation shows that this behavior - returning epoch millisecond date-times - appears to be unique to JSON Bulk Queries and is not specific to `simple_salesforce`. CSV Bulk Query returns the expected ISO date format, as in other Salesforce APIs.

**Comment by thommor** [comment]
Closing as not specific to simple_salesforce
