### ISSUE TITLE
Is there any way to call bulk api asynchronously

### ISSUE THREAD

**Issue by lovejees** [simple-salesforce/simple-salesforce#296]

**Comment by Szasza** [comment]
@lovejees without a more detailed use-case or description on what do you try to achieve it is hard to answer the question properly.

What I do to call the bulk API to create an asynchronous job is:
```
object_type = 'Opportunity'
query = 'SELECT ... FROM ' + object_type
sf = Salesforce(
        username=...
        password=...
        security_token=...
        instance_url=...
        sandbox=... (True or False)
    )

bulk_object_type = getattr(sf.bulk, object_type)
results = bulk_object_type.query(query)
```

If your question is more around "can the batch job's creation be decoupled from the result retrieval?" the answer is unfortunately a "No". As per [this loop](https://github.com/simple-salesforce/simple-salesforce/blob/master/simple_salesforce/bulk.py#L191) the bulk handler will wait for the job to finish before returning.

That being said you can potentially decouple the complete bulk job creation and retrieval into it's own asynchronous wrapper if needed. 

I hope the above helps.

**Comment by ultrarelativistic** [comment]
Yes, it is possible w a little retrofit. See my code suggestion. Just need
to do an async instead of that 'sleep while'.
