### ISSUE TITLE
Bulk API V2 support?

### ISSUE THREAD

**Issue by cjohnsoninc** [simple-salesforce/simple-salesforce#299]
Are there plans to allow use of the Bulk API V2?

**Comment by ultrarelativistic** [comment]
https://developer.salesforce.com/blogs/2017/12/slim-new-bulk-api-v2.html

Correct me if i am wrong. I see SF has simplified the API, which is good. I do not see any new features to their bulk api that have not already been implemented here in some way. Personally, i'd like to see simple salesforce to implement the calls in async mode.

**Comment by nirgal** [comment]
I tried the bulkv2 API for queries, I could not get more than 124 columns in a single query. I don't have that limitation with bulk version 1.
So you might want to stick to version 1, unless you are ready to add some column chunking mechanism & sew them back!

**Comment by Phlogi** [comment]
There are at least different (higher) limitations with the version 2.0, see https://developer.salesforce.com/docs/atlas.en-us.api_bulk_v2.meta/api_bulk_v2/introduction_bulk_api_2.htm

    _Instead of limiting the amount of data uploaded daily by the quantity of jobs, Bulk API 2.0 uses a limit of total records uploaded. The limit is 100 million records per 24-hour period._

As I understand though, the API 1.0 is more flexible. Of course having both would be perfect, so the user can chose according their use case.

**Comment by MattF-Afterpay** [comment]
Anyone managed to find a package that works with Bulk API V2.0?
Having issues with V1 due to character limits of 10million.

**Comment by Phlogi** [comment]
https://pypi.org/project/sfbulk2/ works well for me. I used it with pandas, let me know if you need help, I can share an example.

Jul 6, 2021 09:50:56 Matt Farrell ***@***.***>:

**Comment by MattF-Afterpay** [comment]
> https://pypi.org/project/sfbulk2/ works well for me. I used it with pandas, let me know if you need help, I can share an example.

I'd love to see an example if you could share one!

> Arey you sure V2 does have another character limit though?

According to their [limits page](https://developer.salesforce.com/docs/atlas.en-us.salesforce_app_limits_cheatsheet.meta/salesforce_app_limits_cheatsheet/salesforce_app_limits_platform_bulkapi.htm) the V2 doesn't have the character limit at all, which is the only one I am reaching.

![Screen Shot 2021-07-07 at 7 57 23 am](https://user-images.githubusercontent.com/61439100/124671539-f9416400-def8-11eb-97e1-f9b63570509f.png)

**Comment by jon-wobken** [comment]
I wouldn’t be opposed to adding in support for V2 either within the existing bulk template or defining a new bulk2 method. I like some of the benefits that it provides and if SFDC ends support for Bulk1.0

I’ll look to add this to the growing list of enhancements as I get some free time over the next few weeks.

**Comment by cdubant** [comment]
Has there been any update on bulk V2 since July 13th 2021 ?
We need this support for our implementation and really love simple-salesforce so we would like to keep on using this amazing package/repo 🤩

**Comment by jon-wobken** [comment]
@cdubant - it's on the road map. My goal is to get it added by end of year or beginning of next year depending on timing.

**Comment by sivaramghanta** [comment]
@jon-wobken 
Do we have any target release date for this enhancement?

**Comment by jon-wobken** [comment]
No target release unless someone else wants to start building it out unfortunately I've been caught up with other priorities so have not been able to add this functionality.

**Comment by drbjim** [comment]
@jon-wobken can I take this ticket please?

**Comment by drbjim** [comment]
@jon-wobken Can I get a date for bulk api 2.0 release?

**Comment by cdubant** [comment]
Guys, also looking for the release date.

If a PR already exists, that’s great news!

**Comment by zhiweio** [comment]
Hi, @drbjim @cdubant, maybe you can just use git+https to get the bulk 2.0 feature.

```sh
pip3 install git+https://github.com/simple-salesforce/simple-salesforce.git@feature/bulk_api_2.0
```

**Comment by cdubant** [comment]
Thanks Zhiwei Wang, I didn’t notice that Bulk v2 has already been
implemented since April 25.

Thank you !

Le jeu. 18 mai 2023 à 12:52, Zhiwei Wang ***@***.***> a
écrit :

**Comment by drbjim** [comment]
@zhiweio You are right, however I wanted V2 branch merged to main and published officially

**Comment by jon-wobken** [comment]
Going to try to get is added in this month. Need to rebase onto current version and would like to add additional support to allow passing list of dictionary for CRUD (same way existing bulk functionality works) and returning dictionary for query method

**Comment by drbjim** [comment]
> Going to try to get is added in this month. Need to rebase onto current version and would like to add additional support to allow passing list of dictionary for CRUD (same way existing bulk functionality works) and returning dictionary for query method

got it, let me know if you need any help on that.

**Comment by babaMar** [comment]
> pip3 install git+https://github.com/simple-salesforce/simple-salesforce.git@feature/bulk_api_2.0

Hi @zhiweio any idea whether this branch is going to be merged on `main` soon? And do you know how stable is this branch?

**Comment by jon-wobken** [comment]
Bulk2.0 functionality has been added with v1.12.5 #679

**Comment by babaMar** [comment]
> Bulk2.0 functionality has been added with v1.12.5 #679

It seems this version is not on PyPI yet?

**Comment by jon-wobken** [comment]
This is up now on pypi - there was an issue with a missing line in the readme prevent pypi deployment.
