### ISSUE TITLE
Delete permission sets

### ISSUE THREAD

**Issue by fedee975** [simple-salesforce/simple-salesforce#302]
Hello, We assign permissions to users by 
var = sf.PermissionSetAssignment.create( {'AssigneeId': assigneeId, 'PermissionSetId': permissionSet[0]});

My question is if there is a way to delete the permissions of the user like how can i do that?

thx!

**Comment by Szasza** [comment]
@fedee975 this is more of a SalesForce question than a library-related one.

As per the [SF API documentation](https://developer.salesforce.com/docs/atlas.en-us.api.meta/api/sforce_api_objects_permissionsetassignment.htm) the functions `query` and `delete` are supported.

If you want to remove all of a given user's permission sets, you can try to query the PermissionSet-s for a given AssigneeId first with `sf.PermissionSetAssignment.query(...)`, and then in a loop you can call the `sf.PermissionSetAssignment.delete(...)` with the various PermissionSetAssignmentId-s I got back from the query.

Ideally the above gives a starting point for solving the problem.
