### ISSUE TITLE
Python2 support

### ISSUE THREAD

**Issue by ultrarelativistic** [simple-salesforce/simple-salesforce#306]
Can we drop Python2 support? 

Per python.org "Python 2.7 will not be maintained past 2020". There are several projects now that have dropped support for py2. No new development should be occurring in the community on this version; short of converting the code to py3.

**Comment by nickcatal** [comment]
Operating systems like MacOS don't ship with a python3 distribution (and likely never will) and I've always said it's nice that I can use this project on a command line without installing python3.

On January 1st, 2020 I'm 100% down to stop requiring new releases to pass unit tests on 2.7

**Comment by tonytheodore** [comment]
The latest MacOS (Catalina 10.15) now ships with python3.

**Comment by thommor** [comment]
Will drop support at the end of the year. I don't think this requires an open issue though
