### ISSUE TITLE
constant API calls / logins

### ISSUE THREAD

**Issue by helenfufu** [simple-salesforce/simple-salesforce#325]
Hello! We are trying to upsert ~20k records to a Salesforce object, and ~180k records to another object using the simple-salesforce API. My understanding is that each batch is capped at 10k records, and the bulk.upsert method will upsert 10k for a batch, give this error `InvalidBatch : Exceeded number of records : 10002. Number of records should be less than or equal to 10001`, and then continue to another job with one batch of 10k. Is there a way to group all of the batches under one job?

We are also experiencing constant API logins using the credentials provided to the Salesforce object instance, about one login every 2 seconds to a minute or so, even though our Python callable should only run once an hour. We don't want to exceed our login limit, so we've disabled this for now. 

Are these two issues above related / does anyone have any advice to resolve this? Would be greatly appreciated.

**Comment by ddow** [comment]
In python you can do:
`def chunks(l, n):
    """Yield successive n-sized chunks from l."""
        for i in range(0, len(l), n):
            yield l[i:i + n]`
Then:
`for chunk in chunks(records, 10000):
    upsert chunk with simple-salesforce()
`

**Comment by helenfufu** [comment]
@ddow @Mer-xes thank you both! 

Indeed, had to use batching and limit it to 2-5k records per batch due to how much text was in JSON (apparently salesforce errors if there's more than 10k records OR more than 10mil characters in the payload as well). Wasn't aware that the library didn't handle batching out of the box but thank you for the reference - ended up referring to that exact branch to solve my issue :-).
