### ISSUE TITLE
Is this project alive still?

### ISSUE THREAD

**Issue by whyman** [simple-salesforce/simple-salesforce#326]
Hi,

Is this project maintained still? Seems like there is a big build up of PRs and issues and lack of commits for a number of months.

Is the maintainer still responsive?
Perhaps add some extra people to the Github org? (Currently the organisation is a single person)

Thanks!

**Comment by nickcatal** [comment]
I'm no longer a Salesforce user and haven't had time to keep up with it (I started it as a quick project multiple jobs ago.) I've been adding as a maintainer everyone who wants to be one (including salesforce/heroku staffers.)

Do you want to join in on the project?

**Comment by mohit6up** [comment]
I've just started using the library, and would love to help out.

**Comment by thommor** [comment]
Hi @nickcatal, My organization has recently fully adopted SalesForce and I have more work coming down the pipeline that is likely to be written in Python.

Would you be willing to add me as a maintainer for this project, I am happy to help maintain it and add new features etc.

Cheers

**Comment by tanderegg** [comment]
@nickcatal Might as well add me too while you're at it, we're pretty deep into Salesforce at CFPB these days, so I'm happy to spend some time reviewing PR's.  Hope you're well, by the way, and good luck with your new gig ;)

**Comment by nickcatal** [comment]
@tanderegg added

Hope all is well

**Comment by thommor** [comment]
Any maintainers object to me going through and merging PRs and doing some general house keeping

**Comment by Mer-xes** [comment]
@thommor - None on my end, feel free to add me for anything you want me to review.

**Comment by nickcatal** [comment]
@thommor feel free. when you want a new push to pypi I believe you just tag it with the relevant version number and travis handles it (as long as the tests pass.) If that doesn't work, open a new issue and assign it to me and I'll do a manual push. I'm pretty sure I have all the stuff necessary to do that.
