### ISSUE TITLE
Can't install latest version - stuck at 0.74.3

### ISSUE THREAD

**Issue by tim-sauchuk** [simple-salesforce/simple-salesforce#332]
I installed this package and cannot upgrade past version 0.74.3. However, this version doesn't have batchSize implemented for bulk operations (insert, update, delete).

Any ideas for how to fix this?

**Comment by Mer-xes** [comment]
The version will need to be updated in the project. You can also use the below to add it while that gets updated.

pip install --upgrade git+git://github.com/simple-salesforce/simple-salesforce@master

or

pip install --upgrade --force-reinstall git+git://github.com/simple-salesforce/simple-salesforce@master

**Comment by thommor** [comment]
The latest version on PyPi is 0.74.3.

More releases should be coming down the pipeline soon
