### ISSUE TITLE
Is DuplicateRuleHeader implemented

### ISSUE THREAD

**Issue by thommor** [simple-salesforce/simple-salesforce#337]
Hi,

Was wanting to check whether the DuplicateRuleHeader was implemented and if so how to pass it during the creation of an object?

https://developer.salesforce.com/docs/atlas.en-us.api.meta/api/sforce_api_header_duplicateruleheader.htm

**Comment by adamgross** [comment]
It is -- note that simple-salesforce is based on the REST API, not SOAP, so the appropriate doc reference is:

https://developer.salesforce.com/docs/atlas.en-us.api_rest.meta/api_rest/headers_duplicaterules.htm

Sample Contact create snippet is below:

```
        result = sf.Contact.create({'FirstName':_firstname,
                                    'LastName':_lastname,
                                    'Email':_email,
                                    'RecordTypeId':os.environ.get('CONTACT_RECORDTYPE_ID')},
                                     headers={'Sforce-Duplicate-Rule-Header': 'allowSave=true'})
```
