### ISSUE TITLE
Query Logically Deleted Records

### ISSUE THREAD

**Issue by dlink** [simple-salesforce/simple-salesforce#34]
Hi Love Simple Salesforce.  Thank you for it.

Is there a way to query Logically deleted records?  In other words can it do this:

SELECT Id FROM Contact WHERE isDeleted=true and masterRecordId != null 
  AND SystemModstamp > 2006-01-01T23:01:01+01:00

This query is what Salesforce suggests to know when two records have been merged.

While the simple-salesforce deleted() method returns a list of ids deleted, it does not give the masterRecordId.

The Salesforce restful api supports a 'query_all' to get logically deleted records. However simple-salesforce's query_all is a wrapper around query() and query_more()

Thank you,
David Link
New York

**Comment by maxnaude** [comment]
A workaround is to use the restful method to access to the queryAll end-point on the API, eg:

`sf.restful('queryAll', {'q': 'SELECT Id, Email, MasterRecordId FROM Contact WHERE IsDeleted = TRUE AND MasterRecordId != NULL'})`

**Comment by andscoop** [comment]
Closed by #223
