### ISSUE TITLE
Modify picklist values

### ISSUE THREAD

**Issue by arnoldjos** [simple-salesforce/simple-salesforce#346]
I want to dynamically add values for a picklist in Salesforce, is there a way to add or update picklist values?

**Comment by jon-wobken** [comment]
@arnoldjos - This would require the metadata API which is outside the realm of this package. The easiest way I have found for myself is downloading the PicklistValueSet and object utilizing a tool like ESSA and then modifying the .xml to include that picklist value as well as include it on the desired record type and then re-uploading the metadata package.
