### ISSUE TITLE
Get Records From a Report?

### ISSUE THREAD

**Issue by kylejbrk** [simple-salesforce/simple-salesforce#350]
Is there any way to get all the records for a given report Id?
For example, `sf.Report.get(record_id)` only gives me the metadata about the report, but not the contents.

A similar question was asked here: https://github.com/simple-salesforce/simple-salesforce/issues/58, but that question is a few years old.

**Comment by jon-wobken** [comment]
There isn't a method currently that would allow you to easily get the report data. 

At minimum you would need to use the restful call indicated in that issue and then parse out the column headers and record values.

```
x = sf.restful('analytics/reports/{report_id}',params={
    'includeDetails':'true'})

            
report_columns = x.get('reportMetadata').get('detailColumns')
report_column_details = x.get('reportExtendedMetadata').get('detailColumnInfo')

fact_map = x.get('factMap')

fact_map_values = fact_map.values()
```

I believe after that you would need to loop over to find the dataCells which contains the raw data.

I would recommend checking out https://github.com/cghall/salesforce-reporting for parsing reports as simple_salesforce does not currently have that functionality. I have used that before when needing to parse reports

**Comment by kylejbrk** [comment]
Thank you
