### ISSUE TITLE
JWT Bearer Token workflow release

### ISSUE THREAD

**Issue by DanielDrumond** [simple-salesforce/simple-salesforce#352]
Hi folks,
First, thanks for everyone that helped on this lib, it's awesome!

Well, do you have any calendar of new releases or a prevision with a possible release date with the already done "Support for JWT Bearer Token workflow" feature?

Thank you again! :)

**Comment by jon-wobken** [comment]
@DanielDrumond JWT Bearer Token support was added in on pull #305

**Comment by brianlmoon** [comment]
@jon-wobken Yes, is there a planned release date for a build that includes that change?

**Comment by jon-wobken** [comment]
@brianlmoon - it is already merged into master. It likely just has not updated on PyPi.
