### ISSUE TITLE
When will be the new release?

### ISSUE THREAD

**Issue by alex-todorov** [simple-salesforce/simple-salesforce#355]
Hi there,
I would like to use JWT functionality and was wondering when will be the new release date?
Thanks

**Comment by jon-wobken** [comment]
@alex-todorov - Thought the previous pull request with the JWT token updates had made updates to the version document. Looks like it hasn't so I just made these updates. Will check back and close this out once PyPi shows the update.

**Comment by alex-todorov** [comment]
Great,
Thanks

**Comment by alex-todorov** [comment]
Hey @jon-wobken, 
I still don't see it inside pip, did they approve the release?
Thanks

**Comment by brianlmoon** [comment]
Looks like the builds are failing. Is that why Pypi is not updating? https://travis-ci.org/simple-salesforce/simple-salesforce/builds?utm_medium=notification&utm_source=github_status

**Comment by alex-todorov** [comment]
Hey there,
have you noticed that: NOTE: Try --verbose to see response content.
HTTPError: 403 Client Error: Invalid or non-existent authentication information. See https://pypi.org/help/#invalid-auth for details for url: https://upload.pypi.org/legacy/

It looks like some creds are not right

**Comment by jon-wobken** [comment]
@alex-todorov @brianlmoon - Yep. I've tried updating travis.yml but still having issues. I've asked @nickcatal to check it out as the original person who set it up. 

You can always use pip install git+https://github.com/simple-salesforce/simple-salesforce to download from git.

**Comment by nickcatal** [comment]
A new version is on pypi

**Comment by brianlmoon** [comment]
Thanks so much

**Comment by alex-todorov** [comment]
Great,
thank you!
