### ISSUE TITLE
Increase the default Salesforce API Version

### ISSUE THREAD

**Issue by nickcatal** [simple-salesforce/simple-salesforce#362]
Our current default API version os `38.0` which appears to be from [2017](https://help.salesforce.com/articleView?id=000334996&type=1&mode=1)

We can probably bump that to `42.0` maybe? That's Spring 2018.

**Comment by kokes** [comment]
Yes to this. We've bumped into this issue, where some records were not returned for an older version of the API version. Can't remember the specifics, but it was a weird edge case. Bumping the version in our connstring solved the problem, so I'm all for having a more sensible default.
