### ISSUE TITLE
JWT auth errors out with "expired authorization code"

### ISSUE THREAD

**Issue by bgpr** [simple-salesforce/simple-salesforce#371]
Hi,
       I was trying to use the JWT auth feature from the library and i get a strack trace with "simple_salesforce.exceptions.SalesforceAuthenticationFailed: invalid_grant: expired authorization code" error. 

      I am providing consumer_key, privatekey_file, domain, username as the arguments to get the instance.  Below is the code that was used to make the connection. I have masked personal info. 

```python
C:\Users\XX\simple_debug>python
Python 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from simple_salesforce import Salesforce
>>>
>>> sf = Salesforce(
... consumer_key='XXX',
... privatekey_file='key.pem',
... domain='test',
... username='XXX'
... )
{'iss': 'XXX', 'sub': 'XXX', 'aud': 'https://test.salesforce.com', 'exp': '1584974785'}
Traceback (most recent call last):
  File "<stdin>", line 5, in <module>
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python37\lib\site-packages\simple_salesforce\api.py", line 170, in __init__
    domain=self.domain)
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python37\lib\site-packages\simple_salesforce\login.py", line 181, in SalesforceLogin
    None, proxies, session)
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python37\lib\site-packages\simple_salesforce\login.py", line 256, in token_login
    raise SalesforceAuthenticationFailed(except_code, except_msg)
simple_salesforce.exceptions.SalesforceAuthenticationFailed: invalid_grant: expired authorization code
>>>
```

When i tried using request  + jwt lib (https://pypi.org/project/jwt/) and hit the end points manually, I see it working (i get the access_token and i can access protected resources). I have captured the request payloads in both cases just before jwt encoding happens.

1.
simple-salesforce library payload (which generates the above stack trace)
```json
{'iss': 'XXX', 'sub': 'XXX', 'aud': 'https://test.salesforce.com', 'exp': '1584977424'}
```
2.
manual flow payload. The below is the data to be encoded as jwt after which it is used in the header by requests library (this works)
```json
{'iss': 'XXX', 'aud': 'https://test.salesforce.com', 'sub': 'XXX', 'exp': '1585017068'} 
exp generated out of : int(round(time.time())) + 180
```
Everything else being equal(iss, sub, aud), if i change the exp in the simple-salesforce to a unix epoch + 3 minutes (as per salesforce recomendation ), i get a successful response from simple-salesforce.

https://www.epochconverter.com/ says the exp generated from simple-salesforce was 11 hours ago but the exp from manual flow payload is well within 3 minutes.

Looks to me like a time stamp issue. I am not sure if we can control this at the salesforce end by setting some parameter. I am operating from Sydney, Au (AEST time zone). 

Please have a look and suggest if this is a bug or could be fixed through a setting. Please let me know if you require further info.

Thanks
Prashanth.

**Comment by userkv04** [comment]
It looks like it works only with UTC timezone. My code is in docker which uses UTC timezone. It works perfectly fine there. That can be a workaround for this issue.

**Comment by richard-mah-gv** [comment]
Hi!

Thought I'd chime in as I was trying to figure out the same thing. Here's where I noticed the issue in simple_salesforce\login.py:

```
157        expiration = datetime.**_utcnow_**() + timedelta(minutes=3)
158        payload = {
159            'iss': consumer_key,
160            'sub': username,
161            'aud': 'https://{domain}.salesforce.com'.format(domain=domain),
162            'exp': '{exp:.0f}'.format(
163                exp=**_time.mktime(expiration.timetuple())_** +
164                    expiration.microsecond / 1e6
165            )
166        }
```

It's to do with the value being passed into the **_mktime()_** function. The definition off of the Python website:

> time.mktime(t)
This is the inverse function of localtime(). **_Its argument is the struct_time or full 9-tuple_** (since the dst flag is needed; use -1 as the dst flag if it is unknown) **_which expresses the time in local time, not UTC._** ...

But notice how the assignment of **_expiration_** is made, with **_utcnow()_**. Since **_mktime()_** thinks the value it's being supplied is local time, it converts the time being fed to it instead of using it as is (UTC).

I believe you'll need to correct the calculation for **_expiration_** to be in local time, and **_exp_** to be in UTC.

**Comment by ahmetnarman** [comment]
Hi, I started having the same problem as well, I suspect it is caused by the summer time adjustments in my country. The changes introduced in pull request #431 actually solves the issue for my local machine. When is it possible to merge this pull request?
