### ISSUE TITLE
Issue - Bulk API Upsert/Insert Fails with Json Deserialization

### ISSUE THREAD

**Issue by elangovankrishna** [simple-salesforce/simple-salesforce#372]
Thanks for the great tools and I have been using it for our prod system for 3+ months now.

I had the same error which AAraKKe mentioned on his issues #366 as well when I use a limited number of data for my testing with my full data which is 26K+ records I don't see that issue. Don't want to get into that debugging now.

The other issue that I have been trying to solve for almost 2 days now is described below.
We have a custom salesforce Object and I am trying to load data into it using bulk upsert API, I get the following error for all the rows, its the same error message from SF -> Bulk job -> view result page as well
`ERROR - {"success": false, "created": false, "id": null, "errors": [{"message": "Unexpected JsonMappingException: No such column 'Car_Type__c' on sobject of type Text_Message__c", "fields": [], "statusCode": "INVALID_FIELD", "extendedErrorDetails": null}]}`

The SF Object column that I want to upsert are:

Dealer_ID__c | Number(18, 0)
Account__c | Lookup(Account)
Exception_Inv_Cnt__c | Number(18, 0)
Exception_Text__c | Text(255)
Exception_Type__c | Text(255)
Grain_Type__c | Text(40)
Make__c | Text(255)
Text_ID__c | Number(18, 0)  (External ID)
Vehicle_Segment__c | Text(255)

I have tried to upsert with just individual columns to the SF object just to see if I am able to and I was successful with two columns Text_ID__c and Grain_Type__c alone passing other columns in the upsert input fails with the above error.

I have attached the sample JSON data herewith for reference.
[sf_data.txt](https://github.com/simple-salesforce/simple-salesforce/files/4384533/sf_data.txt)

What could I be doing wrong here? 
Any help or direction would be appreciated.

**Comment by jon-wobken** [comment]
@elangovankrishna - Does the Car_Type__c field exist on that object? Looking at the columns you are upserting, you are including Car_Type__c in your upsert and the feedback is that it does not exist on that object.

**Comment by elangovankrishna** [comment]
@jon-wobken yes I forgot to mention that field above yes it does exist on 
Car_Type__c | Text(255)

**Comment by jon-wobken** [comment]
@elangovankrishna - Can you post your upsert code?

**Comment by elangovankrishna** [comment]
sure here you go 
`
         def upsert(self, object_name, data, external_id_field):
         errors = list()
         self.log.info("Updating %s object" % object_name)
        package = list()
        sf_object = self.get_salesforce_bulk_service(object_name)
        self.log.info(f'External field id  for Salesforce {external_id_field}')
        payload_size = 0
        char_count = 0
        for idx, json_object in enumerate(data):
            payload_size += sys.getsizeof(json.dumps(json_object))
            char_count += len(json.dumps(json_object))

            package.append(json_object)

            if self.MAX_PAYLOAD_SIZE < payload_size \
                    or len(package) > self._bulk_batch_limit() \
                    or char_count > self._is_char_limit():

                self.log.info('Upserting with batch size {} , payload_data_size {} MB , Char_count {}'.format(
                    str(len(package)),
                    str(payload_size / (
                            1024 * 1024)),
                    str(char_count)))
                error_temp = self._upsert_salesforce(package, sf_object, external_id_field)
                if len(error_temp) > 0:
                    self.log.info("Errors : " + str(error_temp))
                errors += error_temp
                package = list()
                '''Reset payload and char_counter'''
                payload_size = 0
                char_count = 0

        # upload the last package
        if len(package) > 0:
            self.log.info('Upserting with batch size {} , payload_data_size {} MB , Char_count {}'.format(
                str(len(package)),
                str(payload_size / (
                        1024 * 1024)),
                str(char_count)))
            error_temp = self._upsert_salesforce(package, sf_object, external_id_field)
            if len(error_temp) > 0:
                self.log.info("Errors : " + str(error_temp))
            errors += error_temp
        self.log.info("Upsert completed")
        return errors
    def _bulk_batch_limit(self):
        # Undercutting sf limit
        return 9995

    def _is_char_limit(self):
        # Undercutting sf limit
        return 9995000

    def get_salesforce_bulk_service(self, object_name):
        sf_conn = self.get_conn()
        return sf_conn.bulk.__getattr__(object_name)

    def _upsert_salesforce(self, package, sf_object, external_id_field):
        result = sf_object.upsert(package, external_id_field)
        #result = sf_object.insert(package)
        return self._append_errors(result)
`

**Comment by jon-wobken** [comment]
@elangovankrishna - Are you sure your user/profile has FLS edit ability on that field?

**Comment by elangovankrishna** [comment]
@jon-wobken It should I can double check that as well, else how come I am able to upsert just for two columns successfully.

**Comment by elangovankrishna** [comment]
@jon-wobken My SF Admin just told me they have made all the fields to have the same access level to my user/profile I am going to run the tests again and get back here with results.

**Comment by elangovankrishna** [comment]
@jon-wobken you were right I dint have proper access on those fields. Got it resolved after the update.
