### ISSUE TITLE
Has your package changed?

### ISSUE THREAD

**Issue by bsank** [simple-salesforce/simple-salesforce#377]
I am using Py 3.7 and 

from simple_salesforce import Salesforce does not resolve
but this
from Simple_Sales_Force import Salesforce

resolves
however I get an error on module Salesforce

Can you update your examples?

**Comment by jon-wobken** [comment]
@bsank - Thats odd, are you sure you have the correct package installed? Nothing has changed for import statement. Can you confirm the version?

**Comment by bharaths-rms** [comment]
I have V1.0.0 simple-salesforce

Here are my import statements
from Simple_Sales_Force import Salesforce

I cannot reference simple_salesforce as your examples state. 

Is this the latest ? https://pypi.org/project/simple-salesforce/

https://pypi.org/project/simple-salesforce/#modal-close

Thanks.

**Comment by jon-wobken** [comment]
@bharaths-rms - Very strange. I'd recommend trying

`pip install --upgrade --force-reinstall simple-salesforce`

and then attempting the import again

`from simple-salesforce import Salesforce`

**Comment by bharaths-rms** [comment]
This worked. Thanks
