### ISSUE TITLE
Create Chatter post with @mention

### ISSUE THREAD

**Issue by Rompol** [simple-salesforce/simple-salesforce#378]
Hi there,
Is there a way I can create Chatter post with mentioning someone?
Thanks,
Roman

**Comment by brookesy2** [comment]
Yes, you can use the restful function with a custom body.

pseudocode
`
body = '{"body": {"messageSegments": [{"type": "Text", "text": "Hello there"}, {"type": "Mention", "id": "userid-to-mention"]}, "feedElementType": "FeedItem", "subjectId": "someCaseId}
session.resftul('chatter/feed-elements/', method='POST', data=body)
`

Basically lifted from here: https://developer.salesforce.com/docs/atlas.en-us.chatterapi.meta/chatterapi/quickreference_post_comment_or_feed_item_with_mention.htm

**Comment by Rompol** [comment]
Tried different ways to use Body segments but it's not working for me.
Input
`sf.FeedItem.create({'ParentId': '0035E00000aaaVQAY',
 'Body':{"messageSegments": [{"type": "Text", "text": "Hello there"}, 
           {"type": "Mention", "id": "00557000007dddAAS"}]}
                        })`
Output
SalesforceMalformedRequest: Malformed request https://dpdhlcsiace--romandevsb.my.salesforce.com/services/data/v38.0/sobjects/FeedItem/. Response content: [{'message': 'Cannot deserialize instance of textarea from START_OBJECT value { or request may be missing a required field at [line:1, column:34]', 'errorCode': 'JSON_PARSER_ERROR'}]

**Comment by brookesy2** [comment]
I should have been more clear. You cannot use FeedItem create as far as I'm aware (if you work it out, would be great to see how!). You can see I specifically mentioned you have to use the restful function.

**Comment by Rompol** [comment]
oh, sad :( 
But your suggestion worked! THANKS!

Jut FYI You are missing " after someCaseId :)

**Comment by brookesy2** [comment]
Awesome, glad it worked :) Yeah I typed the above without paying a lot of attention, I have updated the error.

**Comment by Rompol** [comment]
@brookesy2 OMG, didn't save the code, and now getting the same error, already spend more than an hour trying to figure out the issue, maybe you can have a look? 

`body = {"body":
    {"messageSegments":
    [
        {"type":"Text","text":"Hello"},
        {"type":"Mention","id":"00557000007TkaaaAS"}
        
        ]
        },

    "feedElementType":"FeedItem",
    "subjectId":"0035E00000xqjaaaAY"}

sf.restful('chatter/feed-elements/', method='POST', data=body)`

SalesforceMalformedRequest: Malformed request https://dpdhlcsiace--romandevsb.my.salesforce.com/services/data/v38.0/chatter/feed-elements/. Response content: [{'errorCode': 'JSON_PARSER_ERROR', 'message': "Unexpected character ('b' (code 98)): expected a valid value (number, String, array, object, 'true', 'false' or 'null') at [line:1, column:2]"}]

**Comment by EclesioMeloJunior** [comment]
@Rompol you need to parse your dict to a valid json structure, like that:

```python
feed = {
                "body" : {
                    "messageSegments" : [
                        {
                            "type" : "Text",
                            "text" : "..."
                        },
                        {   
                            "type" : "Mention",
                            "id" : "..."
                        }
                    ]
                },
                "feedElementType" : "FeedItem",
                "subjected" : "..."
}

salesforce_response = self._salesforce.restful('chatter/feed-elements', method='POST', data=json.dumps(feed))

**Comment by Rompol** [comment]
@EclesioMeloJunior Amazing! it works :) Thanks! 
Just note, that you have a mistype "subjected" -> "subjectId"

**Comment by Shivram3339** [comment]
Hey There?

i have output in the following structure

############################## CHECKING FLOW ####################################
 10.211.131.19 [MUM] ---> 10.221.131.19 [DEL] on Port: 22, Protocol: tcp
############################## CHECKING FLOW ####################################

HUNTER OUTPUT FOR MUM FROM ACL
Action: PERMIT

HUNTER OUTPUT FOR DEL TO ACL
Action: PERMIT
I am using the below code to the @mention user and to keep the output in the code block.

text = '' + Hey There  + ''

above text, I can able to post on gus in the code block using the below code.

sf_session.feeditem.create(
{"ParentId": chatter_id, 'Body': text , "Type": "TextPost", "IsRichText": True})

its working but I am told @metion wont work with feeditem hence I have found other way

 body = {
                                        "body": {
                                            "messageSegments": [
                                                {
                                                    "type": "Mention",
                                                     "id": "005B000444403Bs0nxxx",
                                                     },
                                                    {
                                                    "type": "Text",
                                                    "text": text
                                                }
                                        ]
                                    },
                                    "feedElementType": "FeedItem",
                                    "subjectId": chatter_id
                                 }
 sf_session.restful('chatter/feed-elements/', method='POST', data=json.dumps(body))

I am able @mentiond the user but the output is not coming in the code block.



How to achieve both ? such as @mention and code block.
