### ISSUE TITLE
Lazy loading not available in v1.0.0

### ISSUE THREAD

**Issue by Dobatymo** [simple-salesforce/simple-salesforce#385]
According to the changelog https://github.com/simple-salesforce/simple-salesforce/blob/master/CHANGES, lazy loading (query_all_iter) was added in v0.75
But it's not even available in v1.0.0 on pypi. The pull request for this feature was merged May 5, the pypi v1.0.0 release is dated March 20.

It's referenced in the docs already as well https://simple-salesforce.readthedocs.io/en/latest/user_guide/queries.html

**Comment by joshua-nicholson** [comment]
+1, it's very confusing that this function is in the docs but has not been released.

**Comment by jon-wobken** [comment]
@joshua-nicholson @Dobatymo - Just version bumped to 1.10 with updated readme as well as additional features (including lazy loading in query operation). Once Pypi updates I will confirm lazy loading and new bulk functions are included there.
