### ISSUE TITLE
Use session_id from Salesforce to authenticate ?

### ISSUE THREAD

**Issue by yeyeric** [simple-salesforce/simple-salesforce#391]
Hello,

I'd like to use simple-salesforce  to act as the user triggering actions from Salesforce.

For instance, an api call is made from SF to Python, and then I'd like to create an account from Python.

I'm passing the session_id from the  UserInfo.getSessionId() from Salesforce as a header in my api call to Python, but then I'm unable to use simple-salesforce to act as the originating user.

How should I do so ?

I've read https://github.com/simple-salesforce/simple-salesforce/issues/107 and https://github.com/simple-salesforce/simple-salesforce/pull/128 but I don't manage to authenticate, I have an invalid session id error.

I've tried:
```
Salesforce(instance_url="https://cs128.salesforce.com", session_id=session_id)
Salesforce(instance_url="https://cs128.salesforce.com", session_id=session_id, domain='test')
Salesforce(instance="test.salesforce.com", session_id=session_id, domain='test')
Salesforce(instance="test.salesforce.com", session_id=session_id)
```

All of those fail

**Comment by jon-wobken** [comment]
Can you confirm if the user you are using is API enabled?

**Comment by yeyeric** [comment]
Yes the user has system admin profile and api enabled

**Comment by jon-wobken** [comment]
@yeyeric - Can you confirm if a session_id is being created from your Userinfo.getsessionid() login method you are using and is not closed when you are attempting to input the session id for simple-salesforce?

Testing this myself I was able to perform the following (using the simple-salesforce login method to generate my session id and instance url from an existing connection).
```
test_salesforce_login = Salesforce(session_id=sf_full.session_id,instance_url='https://'+sf_full.sf_instance)
test_salesforce_login.query_all("SELECT Id FROM Account LIMIT 1")
```

**Comment by yeyeric** [comment]
Hi again,

I've nailed down the issue and it appears you're right. BUT, I've noted something even stranger.
I have in Salesforce one piece of code which is sending a session_id = A, where another piece of code from Salesforce is sending another session_id = B. The session_id B isn't valid, whereas the A is valid. I swear the code in Salesforce to get the session id is the same.

I've tried replaying several time the scenarios and first scenarios always sends the same token which is valid, whereas scenario 2 in code below always sends another token which isn't valid. All actions triggered at almost the same time without editing anything else on the user or profile in between...

SEND GOOD SESSION_ID (version simplified):
  ```
  @future (callout=true)
    webservice static void sentRequest(string module, string application, string json_string, string access_token)
    {
                Http http = new Http();
                HttpRequest request = new HttpRequest();
                request.setEndpoint('my_end_point');
                request.setMethod('POST');
                request.setHeader('Content-Type', 'application/json');
                request.setHeader('Authorization', 'Bearer ' + access_token);
                request.setHeader('Sf-User', UserInfo.getName());
                request.setHeader('Session-Id', userInfo.getSessionId());
                request.setBody(json_string);
                request.setTimeout(120000);
                HttpResponse response = http.send(request);
            
            }
        }
    }
```

SEND INVALID SESSION_ID (version simplified):
```
@auraEnabled
    public static String sendFormEndOfInterview(String formBody){

        HttpRequest req = new HttpRequest();
        req.setEndpoint('my_end_point');
        req.setMethod('POST');
        req.setBody(formBody);
        req.setHeader('Sf-User-Email', UserInfo.getUserEmail());
        req.setHeader('Session-Id', userInfo.getSessionId());
        req.setTimeout(30000);
        
        String bodyResponse;
        Integer statusCode;
        
            Http http = new Http();
            HTTPResponse res = http.send(req);
            bodyResponse = res.getBody();
            statusCode = res.getStatusCode();

        return bodyResponse;
    }
```
