### ISSUE TITLE
Lead Source is not assigned correctly upon lead cereation

### ISSUE THREAD

**Issue by DandikUnited** [simple-salesforce/simple-salesforce#397]
Whenever I create a lead with the payload, it doesn't pick the lead source correctly upon calling 
 `sf.Lead.Create()`

I've double checked that my payload matches with an existing lookup object's value. Is this a known issue?

**Comment by jon-wobken** [comment]
Can you provide an example of the data you are pushing? The data in the lead source field should be the picklist Api value which may be different than the label.

`sf.Lead.create({'LeadSource':'PicklistApiValue',...})`

**Comment by DandikUnited** [comment]
Sure thing, this is what I post:
```python
lead_object = {
    "FirstName": "Bedi",
    "LastName": "Tester",
    "Email": "test@er.co",
    "Phone": "321 321 1221",
    "LeadSource": "BediTest",
    "OwnerId":owner_id,
    "Company":"Contoso"
}
xre = sf.Lead.create(lead_object)
```

And this is what i have in salesforce's object manager

<img width="789" alt="Screen Shot 2020-06-12 at 10 27 47 AM" src="https://user-images.githubusercontent.com/3067070/84530110-6ef7e380-ac97-11ea-9dd2-af248cdb291a.png">

**Comment by cbohlman** [comment]
@DandikUnited any chance there's some automation updating the Lead Source in your salesforce org? I ran into a similar issue with cases, it turned out there was a process builder running that was changing the field value after creation.

**Comment by DandikUnited** [comment]
Thanks @cbohlma this is the exact cause! Closing this out 👍
