### ISSUE TITLE
INVALID_LOGIN

### ISSUE THREAD

**Issue by alal2255** [simple-salesforce/simple-salesforce#403]
Hello,

Im trying to login use simple-salesforce and getting below error:
simple_salesforce.login.SalesforceAuthenticationFailed: INVALID_LOGIN: Invalid username, password, security token; or user locked out. I am using python 2.7.11. I am using security_token and its valid. Should I be passing a domain ? 

Error:
File "/apps/salesforce/simple_salesforce/api.py", line 147, in __init__
    domain=self.domain)
  File "/apps/salesforce/simple_salesforce/login.py", line 175, in SalesforceLogin
    raise SalesforceAuthenticationFailed(except_code, except_msg)
simple_salesforce.exceptions.SalesforceAuthenticationFailed: INVALID_LOGIN: Invalid username, password, security token; or user locked out.

**Comment by jon-wobken** [comment]
@alal2255 - What version of simple-salesforce are you using? python 2.7 is no longer supported in versions >=1.0.0

**Comment by alal2255** [comment]
i am using __version__ = '0.74.2'

**Comment by jon-wobken** [comment]
Then you should not need to pass the domain (unless you are trying to log into a sandbox environment, then pass either sandbox=True or domain='test'). 

Are you passing the correct username, password, security token, and organizationId? If so, then can you confirm if the user you are using is not locked out or has API access?

**Comment by alal2255** [comment]
I am passing the correct username, password, security token. Hav'nt used organisation id, not sure if that was needed. The user is not locked out

**Comment by jon-wobken** [comment]
Just re-read through the login code. The organization id should not be needed. All that should be needed is

`sf = Salesforce(username='username',password='password',security_token='security_token')`

Unless you are logging into a sand box then it should be 

`sf = Salesforce(username='username',password='password',security_token='security_token',sandbox=True)`

Can you confirm if the user has API access or if you are logging into a sandbox? This is likely some issue with either the user or credentials being passed.

**Comment by alal2255** [comment]
sf = Salesforce(username='XXXX',password='XXXX',security_token='XXXXX',sandbox=True,version='43.0')
  File "/apps/salesforce/simple_salesforce/api.py", line 147, in __init__
    domain=self.domain)
  File "/apps/salesforce/simple_salesforce/login.py", line 175, in SalesforceLogin
    raise SalesforceAuthenticationFailed(except_code, except_msg)
simple_salesforce.exceptions.SalesforceAuthenticationFailed: INVALID_LOGIN: Invalid username, password, security token; or user locked out.

Really not sure why is it giving an error

**Comment by jon-wobken** [comment]
@alal2255 - Can you confirm if the user has API access? If there is any IP filtering in the organization or 2FA with API? This is likely some issue with either the user or credentials being passed or permissions within the org.

**Comment by jakubpas** [comment]
Samw problem here

**Comment by alal2255** [comment]
I had to scrap the idea of using simple_salesforce and develop my own script using python. @jakubpas please check your API endpoint? Login.salesforce.com may not work if you have custom domain/organization domain(assuming password, permissions are all correct)

**Comment by brookesy2** [comment]
Another reason this can occur is because the My Domain is set to prevent logins from login.salesforce.com. You may need to explicitly use domain='whatever.my.salesforce.com'.

**Comment by jakubpas** [comment]
interestingly it works ok with simple-salesforce==0.74.3 so I downgraded
