### ISSUE TITLE
Using format_soql to query SF data

### ISSUE THREAD

**Issue by ppitha** [simple-salesforce/simple-salesforce#408]
Hello, I am trying to query using this model:

from simple_salesforce import Salesforce
sf = Salesforce(**sfc_keywords) # connects me to Salesforce instance
sf.query(format_soql("SELECT Id, Email FROM Contact WHERE LastName IN {names}", names=["Smith", "Jones"]))

However, I get an error 
Traceback (most recent call last):
  File "<stdin>", line 7, in <module>
NameError: name 'format_soql' is not defined

Which makes sense with format_soql unqualified. I tried using sf.format_soql but that doesn't work either. I can see it's a type:
>>> sf.format_soql
<simple_salesforce.api.SFType object at 0x1037e9790>

but what am I missing?

**Comment by AndiEcker** [comment]
Long time not using this library ...

seems that `format_soql` is an (callable?) object (not a type).

Try to reference `format_soql` via the `sf` object:

`sf.query(sf.format_soql("SELECT Id, Email FROM Contact WHERE LastName IN
{names}", names=["Smith", "Jones"]))`

HTH

Am Mi., 22. Juli 2020 um 22:07 Uhr schrieb Phil Pitha <
notifications@github.com>:

**Comment by jon-wobken** [comment]
@ppitha - Will make an update to this on the readme. Correct readme should note it would need to be imported from simple_salesforce as

`from simple_salesforce import format_soql, format_external_id`

**Comment by ppitha** [comment]
Thanks @jon-wobken @AndiEcker ! I left this project but I'm sure it will help future developers. Most important was I was not on the latest version :)
