### ISSUE TITLE
METHOD_NOT_ALLOWED : Cannot use any update or upsert methods! PLEASE HELP URGENT!

### ISSUE THREAD

**Issue by albisbub** [simple-salesforce/simple-salesforce#412]
[SalesforceGeneralError('https://menstrual.my.salesforce.com/services/data/v38.0/sobjects/Account/', 405, 'Account', [{'errorCode': 'METHOD_NOT_ALLOWED', 'message': "HTTP Method 'PATCH' not allowed. Allowed are HEAD,GET,POST"}])]

def  UpdateChapter(og_name, upsertingData, sf):
    id_ = getChapID_byName(sf, og_name)
    print(id_)
    sf.Account.update(id_, upsertingData)

This code has run smoothly for months, but today it gives me this error. Anyone have the same issue or need a fix, would appreciate it!

**Comment by jon-wobken** [comment]
@albisbub - You need to use API version >=42.0 and it looks like the url referenced is using v38.0. 

Can you confirm which version of simple-salesforce you are using? If you are using an older verison, you may need to specify the version argument in the Salesforce object you use for authentication

**Comment by albisbub** [comment]
I'm using simple-salesforce==0.74.2 but I'm setting up a new virtual environment and gonna do a fresh install to see if that helps. thanks for the speedy reply!

**Comment by jon-wobken** [comment]
Ah - Yes then it is likely that you were running off the default API version which I believe was 38. Check out the notes as there are several new features if you are moving over from 74.2 and some python versions have been dropped from support in >=1.0.0

**Comment by albisbub** [comment]
so i updated and included version=42.0 and I still get the same error message

**Comment by albisbub** [comment]
wait its still giving me the error message but its working! strange

**Comment by jon-wobken** [comment]
Very strange - what are you sending via upsertingData. I can try to see if I can replicate in one of my orgs. I have never experienced or seen this error.

Can you confirm current version, python version, and data that is being sent in id__ (is it the actual account id or is potentially data that doesn't exist in the org?) and in the upsertingData? Even just an example such as {'FirstName':'Test','SomeRelatedField__r':{'External_Id__c':'Data'},'Lastname':'test'}?
