### ISSUE TITLE
Assigning Lead Owner in Lead creation

### ISSUE THREAD

**Issue by P-Rainbow** [simple-salesforce/simple-salesforce#419]
Thank you for creating and sharing this very useful and convenient package!

I'm using below lines (Python) to create a Lead in Salesforce.

In the field "OwnerId", I put in my user ID in the Salesforce Object format (15 digits).

But the Lead successfully created doesn’t show me the Lead Owner.

It seems like the field “OwnerId” is not for Lead Owner. What's the right field?

By the way, is there a place that I find the full list of the items in the lead_object = {}?

Thank you.

`from simple_salesforce import Salesforce

sf = Salesforce(username= "user_email"
                ,password= "password"
                ,security_token= "sec_token")

lead_object = {
    "FirstName": "John",
    "LastName": "Kane",
    "Phone": "321 321 1221",
    "OwnerId": "15_digit_Salesforce_Object_style",
    "Company":"Engineering Co., Ltd"
}

xre = sf.Lead.create(lead_object)
print (xre['id'])`

**Comment by gabriel-dallas** [comment]
I have this issue where it is correctly pulling lead owner, but upon any update, it is changing lead owner to Admin

**Comment by capitalhumain** [comment]
Just in case anyone needs, this is the way that we figured out to take ownership of a lead using simple_salesforce:
headers = {'Sforce-Auto-Assign': 'False'}
sf.Lead.update(case_id, {'OwnerId': user_id}, raw_response=True, headers=headers)

**Comment by P-Rainbow** [comment]
@capitalhumain , brilliant!
