### ISSUE TITLE
Request: Id Growth Formula on utils

### ISSUE THREAD

**Issue by llazzaro** [simple-salesforce/simple-salesforce#42]
If you are working in a case-sensitive system, the first 15 characters is enough for it to be a unique Id.
if you have the 15 character Id you can generate the last three characters to compose the 18 character Id.

Let me know if anyone disagress into adding this formula to utils, I can code it by myself.

**Comment by andscoop** [comment]
@llazzaro Wow this is an old one, do you have any context around this issue? What problem were you looking to solve?

**Comment by llazzaro** [comment]
I don't remember. 
Too much code syndrome.
Closing this issue for now.
