### ISSUE TITLE
How to upsert to a lookup field?

### ISSUE THREAD

**Issue by emskiphoto** [simple-salesforce/simple-salesforce#424]
**What is the command syntax to upsert to a lookup field (related type field)?**   

I would like to update the 'EEE__c' field on the Opportunity object.  This is a lookup field.   When I attempt to update using the command below

`xcelsf.Opportunity.update(Id, {'EEE__c' : 'John Doe'}, raw_response=True) `

this error is returned:  
Response content: [{'message': 'EEE: id value of incorrect type: John Doe', 'errorCode': 'MALFORMED_ID', 'fields': ['EEE__c']}]

I know the relationship(?) is:
'relationshipName', 'EEE__r'

**Comment by ddow** [comment]
You need to put John Doe's contact ID there, not his name. Should look something like: {'EEE__c' : '0030f00207jWivmADC'}

**Comment by jon-wobken** [comment]
@emskiphoto - @ddow  is correct, you need to include the 15 digit or 18 digit id into that field. If you are attempting to update a lookup through an external id you need to have a sub dictionary using __r (if its a custom field) and then the external id field. The Salesforce development site has a good example here: https://developer.salesforce.com/docs/atlas.en-us.api_rest.meta/api_rest/dome_upsert.htm . The only nuance is for standard fields which would not use __r (example: the account field on contact would use AccountId in place of EEE__r in your example).

```
{'EEE__r':
    {'External_Id__c':'ExternalIdValue'}
}
```
