### ISSUE TITLE
Salesforce to Salesforce Migration

### ISSUE THREAD

**Issue by amitinfo86** [simple-salesforce/simple-salesforce#425]
We are doing Salesforce (old instance) to Salesforce (new instance) migration. We have Standard and custom objects in our old instance which are needed to be migrated to the new Salesforce instance. We are doing this in the following steps:-

1: Using salesforce describe rest api create tables in MySQL with similar mapping of salesforce object. Tables are created with referential integrity using "referenceTo" field of describe call. Example: services/data/v49.0/sobjects/User/describe/.

2: Get data from salesforce using query rest api and put into MySQL tables. Example: /services/data/v39.0/query/?q=.

3: In this part, we have some confusion like which api we should use so that we can push records to destination org.

Bulk api batch results do not return newly created Id in destination org which we need to update in child records. Composite API return newly created Id with reference Id (which is old id, so that we can update child object in MySQL before sending them). Composite API have a limit of 200 records in a single request.

**Comment by jon-wobken** [comment]
@amitinfo86 - The bulk api batch should return the newly created id, however, the returned IDs are returned in the order that the batches finished. I'd recommend handling this through an external id and using the id of your source organization as the external id and reference it when you create child record. For example, Account.External_Id__c = '123'. Then the child records would use the following

`{'Field_0__c':'ABC','Account':{'External_Id__c':'123'},'Field_1__c':'123'}'`

I would handle it similar to the steps you are doing (I have in the past created mappings from SFDC to SQL data types which I am assuming you are handling as well in your process and then using the field name/mapping to create my object table. I usually store one table in the database that contains the relevant objects I want to replicate, one table that stores the fields and field mappings for those objects that I then query and use to create my physical tables in the DB for that object.

1) Describe relevant objects/fields and create tables in DB
2) Query field table in DB for that object and then use this to generate your SOQL statement for that object and use the query_all function to get all records. Parse the records, add external id field (as key in the dict) with source id as the value and remove the original id key. 
3) Generate list of dictionaries, when there is a referenced look up field then use the relationship api name with the nested dictionary containing the external id field and value
4) Insert using Bulk upsert records
