### ISSUE TITLE
Question: collecting Salesforce Leads (and more)

### ISSUE THREAD

**Issue by seanmcfeely** [simple-salesforce/simple-salesforce#429]
Hello, 

This is not an issue, this is a question and can be closed immediately, if needed.

I've looked around a bit and this library looks like the best solution for programmatically querying Salesforce Leads (and potentially other things?), and then pulling the content. We want to do this so we can scan the content for maliciousness with our detection engines. This library can do that easily, correct?

Before I jump in further, I was wondering if there were any community members out there willing to 1.) make sure I'm not missing something big (I am a 100% noob to the Salesforce world and it's vocabulary) and 2.) potentially point me in any helpful direction with some code or salesforce documentation I should read first.

Thank you,

Sean

**Comment by jon-wobken** [comment]
@seanmcfeely - Sorry for the late reply, finally had some time to make headway on this. If you still need help/have questions feel free to reach out to me and I'd be happy to walk you through both simple-salesforce as well as anything I can for general Salesforce.com (data, api calls, etc). From a SFDC/API documentation I would recommend checking out their REST api developer site. This will probably be most of what you need to start with (querying/creating/updating/deleting records) https://developer.salesforce.com/docs/atlas.en-us.api_rest.meta/api/using_resources_working_with_records.htm?search_text=insert

**Comment by seanmcfeely** [comment]
@jon-wobken thanks for the reply and the offer. I was able to solve my specific problem for the time being by collecting out front of the salesforce pipeline. There is still a chance I may have to integrate with salesforce API directly at a later date. I will very likely use this library at that time. Thanks!
