### ISSUE TITLE
Question: Which REST API is being used?

### ISSUE THREAD

**Issue by feraljuicebox** [simple-salesforce/simple-salesforce#430]
With the recent notification that REST v21.0 thru v30.0 are no longer being supported, I decided to check which version of the API this utilizes.  I was not able to identify that.  Can you please update the documentation to list this information?

**Comment by Phlogi** [comment]
https://github.com/simple-salesforce/simple-salesforce/blob/master/simple_salesforce/api.py

```
# has to be defined prior to login import
DEFAULT_API_VERSION = '42.0'

```
