### ISSUE TITLE
Simple Salesforce and Multi-Factor Authentication

### ISSUE THREAD

**Issue by Rompol** [simple-salesforce/simple-salesforce#432]
Hi there,  Since we activated Multi-Factor Authentication in our SF, I can't connect to it anymore. Is there a way it can be fixed?    

I was using just a username and password to log in.

`session_id, instance = SalesforceLogin(username = sf_username, password =   sf_password, sandbox = False)   

sf = Salesforce(instance = instance, session_id = session_id)`

**Comment by jon-wobken** [comment]
@Rompol - If you have a connected app you can use the consumer key/username and private key to login (JWT bearer authorization) or if you have logged and have admin access you can login and then pull the session_id out to use in the Salesforce login call. I am not as familiar with the login API process with multifactor authentication. You may also need to have your ip address whitelisted in your org to allow the API to login.

Some additional reading - https://developer.salesforce.com/docs/atlas.en-us.api.meta/api/sforce_api_concepts_security.htm

**Comment by Rompol** [comment]
@jon-wobken Thanks! I think I found the solution to this one. When you have MFA activated, and you have a mobile app (SF Authenticator). You just enter your password followed by the code from the app

[https://developer.salesforce.com/docs/atlas.en-us.api.meta/api/sforce_api_concepts_security.htm ](https://developer.salesforce.com/docs/atlas.en-us.api.meta/api/sforce_api_concepts_security.htm )
_A security token is a generated key from Salesforce. For example, if a user’s password is mypassword and the security token is XXXXXXXXXX, the user enters mypasswordXXXXXXXXXX to log in._

**Comment by jon-wobken** [comment]
@Rompol - That is very helpful information. I'll look to add that to the readme
