### ISSUE TITLE
query to pandas dataframe feature

### ISSUE THREAD

**Issue by bsalihklick** [simple-salesforce/simple-salesforce#433]
since pandas dataframe is used for various data analysis, 'query to dataframe' feature would add lots of values in bulk.py

**Comment by jon-wobken** [comment]
@bsalihklick - I've got some existing code I use for this personally. I can look to get a pull request for it. Though, one issue that I know I have experienced when handling it this way is memory errors occurring on larger queries.

**Comment by tsabat** [comment]
Please don’t make pandas a requirement of simple salesforce. The size of the lib is too large for projects that don’t need it.  For example, when adding pandas and numpy (a requirement of pandas) an aws lambda requiring it becomes too large to edit inline.  Projects I use with pandas require a separate lambda layer.  I’d make this an optimal contrib library rather than a requirement of simple salesforce

**Comment by jon-wobken** [comment]
@tsabat - great point. I had no considered the implications of that yet. Likely would be better off as a helpful function in the readme.

**Comment by tsabat** [comment]
@Ed1123 how would you handle pip requirements?  This feels like a call for a contrib library or plugin.

**Comment by Ed1123** [comment]
I'm not sure, but I've came across packages that have methods that
optionally work with other given package. I remember a fuzzy search package
(fuzzywuzzy) which have a method that performs faster searches if you
choose to install another package. It give you a warning that you don't
have install that package and tells you that you could installed for better
performance.

I can do some research and work on it if you want. :)

**Comment by tsabat** [comment]
Sounds good.  I come from the ruby world where your package won’t build without all your dependencies installed.  If this is a common python package I don’t have objection. I also don’t maintain this lib, fwiw.

Tim Sabat

813-785-8013

**Comment by Ed1123** [comment]
I'm gonna work on it then. Do you know how should be the process? Shall I opened a new issue, pr, wait for a maintainer to assign the issue to me or what? I'm kind of new to GitHub. ^^u
