### ISSUE TITLE
The latest pypi's version is 1.10.1.

### ISSUE THREAD

**Issue by TitanFighter** [simple-salesforce/simple-salesforce#437]
Hi.

The package has not been updated on pypi -> https://pypi.org/project/simple-salesforce/#history

If anyone needs, alternative solution to install it: `pip install https://github.com/simple-salesforce/simple-salesforce/archive/master.zip`

**Comment by armaandhull** [comment]
@jon-wobken possible to fix this?

**Comment by gaoqiang-zhuo** [comment]
Who could help release the latest version 1.11.0 to pypi? Thanks.

**Comment by armaandhull** [comment]
@jon-wobken bumping this up

**Comment by ruiyang2015** [comment]
would like to get the latest 1.11.0 in pypi too. it breaks our workflow. We only use pypi in our deploy flow. can not use the github link directly.

**Comment by prasrvenkat** [comment]
We would also appreciate if 1.11.0 is published to pypi as well

**Comment by jon-wobken** [comment]
This has been fixed and PyPi is now updated with 1.11.1 with some additional features.
