### ISSUE TITLE
Need some help...

### ISSUE THREAD

**Issue by promentis** [simple-salesforce/simple-salesforce#440]
I'm trying to debug an error that started showing up a few weeks ago--I only just learned about it. I didn't write the code and I'm not very familiar with python, but willing to learn if someone can point me in the right direction.

As best as I can tell, the query is returning more than 10000 records (batch_size) and is not processing that correctly.

Here are the errors I'm getting:

![image](https://user-images.githubusercontent.com/4504066/103426813-ed06d380-4b70-11eb-8414-f0c9d17a5af5.png)

Thanks for any help on how to resolve!

**Comment by jakedave** [comment]
You might have already solved the problem, but I'd start with upgrading to the latest version of simple_salesforce (along with moving to python3).  The error message looks like it is citing [code from three years ago](https://github.com/simple-salesforce/simple-salesforce/commit/58a729bea98a70b0436b08834cdc18ea704b531d#diff-71e33cbbbd27d12c0862c7d23c3169ce512ade4cd84290662d6b35e1a767a703)

**Comment by jon-wobken** [comment]
Python 2.7 is no longer supported in the new version and so the current readme contain arguments that might not be in the previous version.
