### ISSUE TITLE
Run queries using auth token

### ISSUE THREAD

**Issue by AllanOricil** [simple-salesforce/simple-salesforce#456]
I already have the access token given by our pipeline. I would like to use this lib to query stuff but I cant see a way of doing so using my access token.

**Comment by hkajiwara** [comment]
@AllanOricil _Salesforce_ instance has _session_id_ parameter and you could use it with the access token.

`sf = Salesforce(instance='<instance url>', session_id='<access token>')`

**Comment by AllanOricil** [comment]
@hkajiwara I just have the access token that I get from sfdx. The session I'd is not available. How can I use this Salesforce object then?
