### ISSUE TITLE
Future Requirement to Enable Multi-Factor Authentication (MFA)

### ISSUE THREAD

**Issue by whoishe1** [simple-salesforce/simple-salesforce#457]
Hey guys,

I'm currently accessing Salesforce using the security token method

```
from simple_salesforce import Salesforce
sf = Salesforce(username='myemail@example.com', password='password', security_token='token')
```

But Salesforce recently released a statement requiring an additional Multi-Factor Authentication security authentication:

`https://help.salesforce.com/articleView?id=000356005&type=1&mode=1` ,  

If I have MFA enabled on my account (forced in Feb 2022), I cannot access the instance.
Will there be a future solution to bypass this?

**Comment by whoishe1** [comment]
one solution for this, if authenticating and gaining access with a security token is to create an API user only.  Once the API user is created, you need to contact your admin and reset the security token, which will then be found under the email of the API user.

**Comment by punnerud** [comment]
My solution was to use the Postmans premade collection for SalesForce.
When I click "Get NewAccessToken" it automatically login in and do the callback using Oauth2 (remember to click the popup). Then you get an access token that can be used in the same way as session_id.

sf = Salesforce(instance_url='https://YOURINSTANCE.my.salesforce.com', session_id='YOUR_ACCESS_TOKEN')

Quick search is a fast way to check if you are connected:
sf.quick_search("test")

<img width="872" alt="image" src="https://user-images.githubusercontent.com/1153515/231685655-338e6bb4-97d9-42f8-b1f0-d4295f49aa8a.png">

Did not get any of the default simple-salesforce login to work out of the box with Oauth2.
