### ISSUE TITLE
Way around 10k batch size to update more than 10k accounts with bulk update?

### ISSUE THREAD

**Issue by wombat9375** [simple-salesforce/simple-salesforce#458]
Hello,

Is there a way to work around the batch size of the bulk update method to update more than 10k accounts? 

Im trying to update 14k accounts and the method always returns only around 9.5k - 10.5 k successful updates.

Thanks,

Alex

**Comment by hkajiwara** [comment]
Looks like the maximum batch size is limited to 10K as the [doc](https://developer.salesforce.com/docs/atlas.en-us.230.0.salesforce_app_limits_cheatsheet.meta/salesforce_app_limits_cheatsheet/salesforce_app_limits_platform_bulkapi.htm) says. Given that only a part of 14K is updated, I would say the subset of the batch job should fail to update the records somehow in server side.

**Comment by jon-wobken** [comment]
@wombat9375  - v1.11.2 supports automated batch sizes. For example, if your data contains 14k rows, it will automatically parse this into two batches of 10k and 4k within a single job.
