### ISSUE TITLE
CRUD-Based Metadata operations

### ISSUE THREAD

**Issue by pranav-dahiya** [simple-salesforce/simple-salesforce#460]
Is implementing CRUD-Based metadata operations on the roadmap? I need it for a project I am working on. I am willing to implement it myself if no one else needs this. But I am relatively new to Salesforce, and some help would be appreciated

**Comment by jon-wobken** [comment]
@pranav-dahiya - So far the only thing that has been added is the ability to deploy change sets through the metadata API. I have been planning to add support for the tooling API which supports most CRUD-Based Metadata operations but time has unfortunately been limited.

Feel free to contribute - I'd be happy to lend support as well to get it incorporated faster.

**Comment by pranav-dahiya** [comment]
@jon-wobken I will come back to this in 4-6 weeks. I have taken on another project in the meantime. Some support would be really helpful. Will reach out once I start working on it.

**Comment by pranav-dahiya** [comment]
I have implemented these features and created a merge request. https://github.com/simple-salesforce/simple-salesforce/pull/475
