### ISSUE TITLE
pip 1.11.0

### ISSUE THREAD

**Issue by anthonygiuliano** [simple-salesforce/simple-salesforce#462]
not sure if it's because of the version of python i'm using, but pip doesn't seem to know about version 1.11.0.  I can only get it to upgrade to 1.10.1

is 1.11.0 supposed to be available to upgrade to?

**Comment by default1337** [comment]
python -m pip install git+https://github.com/simple-salesforce/simple-salesforce.git  should help you install the current version from github.
