### ISSUE TITLE
v1.11.1 bulk results

### ISSUE THREAD

**Issue by mhogg-srg** [simple-salesforce/simple-salesforce#469]
Prior to v1.11.1 (and v1.11.0 I think, though I haven't tested because that version is absent on PyPI), the following code would have produced a one dimensional list of dicts, like so:

    >>> results = sf.bulk.Contact.insert([{'LastName': 'Test'}])
    >>> print(results)
    [{'success': True, 'created': True, 'id': '0031g00000nakPdAAI', 'errors': []}]

With v1.11.1, a two-dimensional list is returned; I believe the top level represents batches:

    >>> results = sf.bulk.Contact.insert([{'LastName': 'Test'}])
    >>> print(results)
    [[{'success': True, 'created': True, 'id': '0031g00000nakAEAAY', 'errors': []}]]

Was this an intentional change, and if so, where is it documented?

**Comment by brno32** [comment]
I've noticed this is as well. This has broken some projects for me so I'll be locking to a previous version

**Comment by tsabat** [comment]
same problem here.  this breaks all previous projects if we simply upgrade the package.

**Comment by jon-wobken** [comment]
Unintentional - will look to got fix this. Haven't had a chance to dive into it so not sure what change caused this as there were minimal changes to the bulk operation.

**Comment by brno32** [comment]
Looks like on line 228 of `bulk.py`, that `i` is actually a list

```python
results = [i for sublist in list_of_results for i in sublist]
```

Maybe this would fix it?

```python
results_generator = pool.map(multi_thread_worker, batches)

results = [
    result
    for batch_results in results_generator
    for batch in batch_results
    for result in batch
]
```

**Comment by tsabat** [comment]
Hello All.  Can we get this into main?  We're gonna have to fork to move forward with newer features.  It'd be great not to have to.

**Comment by jon-wobken** [comment]
@tsabat / @brno32  / @mhogg-srg - implementing this fix for this tonight to have the results unpack the third layer down per @brno32's change just need to adjust the test since its not passing.

**Comment by brno32** [comment]
I see 1.11.2 went out yesterday. Are we all good to go?

**Comment by tsabat** [comment]
@brno32 seems like it. 

https://github.com/simple-salesforce/simple-salesforce/commit/9f62f4f43163f8845a3534e3fdb3effef7dc5711#diff-aac07aefec754086f5c344e2c233862f6a611c739b5647fd456c1b77d3577c79R1

**Comment by brno32** [comment]
Looks like 1.11.2 hasn't been published to PyPi yet

**Comment by jon-wobken** [comment]
@brno32 - Unfortunately looks like the travis-ci integration that pushed the deployments to pypi is out of credits so I'll need to push it manually instead of relying on travis-ci

**Comment by saosebastiao** [comment]
@jon-wobken not sure if this got lost, but it looks like the manual push didn't work, and it looks like there was a travis build 5 days ago, but one of the targets failed. 

https://travis-ci.com/github/simple-salesforce/simple-salesforce

**Comment by jon-wobken** [comment]
@saosebastiao - updated to take care of the travis-ci/pylint errors. Going to see if it automatically picks it back up in the next day or so and deploys it.

**Comment by brno32** [comment]
`1.11.2` isn't on pypi as of yet. https://github.com/simple-salesforce/simple-salesforce/issues/486 reports this

**Comment by jon-wobken** [comment]
@brno32  - Took a bit longer than expected but got the Travis-CI fixed and pypi is now updated.
