### ISSUE TITLE
Flag for using an ordinary `dict` in the API response

### ISSUE THREAD

**Issue by brno32** [simple-salesforce/simple-salesforce#477]
Currently, `_call_api` returns results as an `OrderedDict`. Could an optional flag be added to instruct the class to not make this transformation when pulling down the response as JSON?

**Comment by sohithkumar** [comment]
@brno32 @jon-wobken  I have raised a pr which will make the json response to use dict if needed by the user. 
I created a object_pairs_hook parameter which by default uses OrderedDict (to be consistent with default json response by the package. User can pass either dict or None option to this parameter while calling if a dict json response is required.

**Comment by jon-wobken** [comment]
This is resolved in >=1.12.0
