### ISSUE TITLE
How to interact with button?

### ISSUE THREAD

**Issue by EnduringGuerila** [simple-salesforce/simple-salesforce#483]
I am trying to automate the creation of Partner Users in our Salesforce. 
We have a button on the Account page saying "Enable as Partner", then on the linked contact "Enable as Partner User"

Is there a way to interact with these buttons, or, some other way to enable partner users via the API?

**Comment by hkajiwara** [comment]
Hi @EnduringGuerila,

You can create Partner Users as just creating User with ContactId attribute as bellow.

```
sf = Salesforce(...)
partner_user = sf.User.create(
    {
        'Username': 'partner1@issue483.com',
        'LastName': 'Partner1',
        'Email': 'partner1@issue483.com',
        'Alias': 'partner1',
        'TimeZoneSidKey' : 'America/Los_Angeles',
        'LocaleSidKey' : 'en_US',
        'EmailEncodingKey' : 'ISO-8859-1',
        'ProfileId' : '00exxxxxxxxxxxx',
        'LanguageLocaleKey' : 'en_US',
        'ContactId': '003xxxxxxxxxxxx'
    }
)
```
