### ISSUE TITLE
Want to join the group and make this library better

### ISSUE THREAD

**Issue by abhijit-sathe** [simple-salesforce/simple-salesforce#484]
Hi All, 
I have been working on Salesforce for couple of years now and also developed python jobs for downloading uploading files in bulk from salesforce. I want to join the group and make this library better 
How can i start? 

thanks
Abhijit

**Comment by jon-wobken** [comment]
Hi Abhijit- if there is a feature you feel is missing or functionality you wish to enhance feel free to contribute an make a pull request.

a couple features I am working on to enhance for end of year:
- bulk load job does not close/sends blank batch
- Add support for bulk api 2.0
