### ISSUE TITLE
Upserting with a CSV file

### ISSUE THREAD

**Issue by Parth-kbs** [simple-salesforce/simple-salesforce#487]
How can we bulk upsert via a CSV file? Specifically to the CampaignMembers object.

**Comment by jon-wobken** [comment]
@Parth-kbs  - You can read your CSV to a pandas dataframe, or create your own dict with csv reader and then create the list of dicts to upload using the standard command or use salesforces's data loader. Currently, native CSV uploads (as SFDC supports JSON and CSV data in the API) are not supported as we are only passing JSON with our calls.
