### ISSUE TITLE
Bulk upseting to Custom Object

### ISSUE THREAD

**Issue by Parth-kbs** [simple-salesforce/simple-salesforce#488]
How would one upsert to a custom object? Is it possible to just do it this way?

`sf.bulk.CustomObject.upsert()`

**Comment by jon-wobken** [comment]
@Parth-kbs  - Correct. You would use the API name (example: sf.bulk.CustomObject__c.upsert()). The standard objects do not contain an "__c" at the end of the object name (example: sf.bulk.Lead.upsert() or sf.bulk.Account.upsert()).
