### ISSUE TITLE
Salesforce API Versions 7.0 thru 20.0 Retirement

### ISSUE THREAD

**Issue by tim-sauchuk** [simple-salesforce/simple-salesforce#505]
Salesforce noted that they'll be retiring older versions of their API endpoint on May 1, 2022:

https://help.salesforce.com/s/articleView?id=000351312&type=1

Will this package be affected by this retirement, or do you not use any APIs with version 20.0 or older?

**Comment by jon-wobken** [comment]
The api default is 42 so it will not be effected by this retirement.

**Comment by tim-sauchuk** [comment]
Thanks @jon-wobken . I've reached out to SFDC to make sure they note that simple-salesforce will still be supported on their article regarding the feature retirement:

https://help.salesforce.com/s/articleView?id=000351312&type=1
