### ISSUE TITLE
Set_password -- Resource not found

### ISSUE THREAD

**Issue by johnsovo44** [simple-salesforce/simple-salesforce#509]
Hi,
I've been trying to use the set_password method inside this library and continue to get after several tries the following:

> SalesforceResourceNotFound: Resource  Not Found. Response content: [{'errorCode': 'NOT_FOUND', 'message': 'The requested resource does not exist'}]

1. What does this mean?
2. Is it even working?
3. How do you get it to work if it is working as it should?

currently I'm entering in the record ID of the user and creating a random password that is 9 characters long and alphanumeric plus special characters.

**Comment by johnsovo44** [comment]
Hey jumping in here to confirm something. 

You said this the first time we talked:
_"I tested set_password method with the **latest version**"_

When you say version do you mean the API version? Does it need to be 51 and above? I just discovered ours might be 42. Or do you mean the version of simple salesforce?

Thanks.

**Comment by hkajiwara** [comment]
I mean this simple-salesforce version.

**Comment by johnsovo44** [comment]
Re-opening this:

We got this to work finally some time ago, but now I have questions about the password change:

We can change the password, but how do you notify the user? We noticed not automatic email is sent out if you do it through the API but will be sent out if you do it through the platform.

**Comment by hkajiwara** [comment]
@johnsovo44 

_simple_salesforce_ lib just leverages **_User_** sObject REST resource. According to the docs of [sObject User Password](https://developer.salesforce.com/docs/atlas.en-us.api_rest.meta/api_rest/resources_sobject_user_password.htm) and [Manage User Passwords](https://developer.salesforce.com/docs/atlas.en-us.api_rest.meta/api_rest/dome_sobject_user_password.htm), it appears there is no notification feature on this resource.

**Comment by jon-wobken** [comment]
Closing this issue as set_password does not support sending out a notification per salesforce documentation.
