### ISSUE TITLE
Salesforce Platform API Versions 21.0 through 30.0 Retirement

### ISSUE THREAD

**Issue by oded-regev** [simple-salesforce/simple-salesforce#516]
Hi,

Following https://help.salesforce.com/s/articleView?id=000354473&type=1 - I just want to understand what it means for me as a user of this library of version `1.11.3`.

Did I understand it correct that the API version in use is v42?

Thanks

**Comment by hkajiwara** [comment]
DEFAULT API VERSION is 42.0 and you can specify the version with **_version_** parameter when creating Salesforce instance.

`sf = Salesforce(..., version='53.0')`

**Comment by oded-regev** [comment]
That's excellent, thanks
