### ISSUE TITLE
When a Bulk API batch state is 'NotProcessed' the _bulk_operation method sleeps forever.

### ISSUE THREAD

**Issue by magardner** [simple-salesforce/simple-salesforce#517]
Hi,

I noticed this when playing with the Bulk API. When I have a bulk job where one of the batches is not processed the _bulk_operation method appears to hang as it sleeps waiting forever. This is because the code on Line 185 checks for the state = 'Not Processed' however the actual value returned by the Salesforce API is 'NotProcessed' without the space.

I can reproduce this by adding the PK chunking header to the request as this seems to create an empty batch within the job that causes the worker checking the result to fail.

https://github.com/simple-salesforce/simple-salesforce/blob/30ad772f81935b604b6461e17e1c92c16f77f9b2/simple_salesforce/bulk.py#L185

Here is an example of the response from the Salesforce API when querying the status of the batch.

![image](https://user-images.githubusercontent.com/5609949/144244630-802e4910-3a44-43ef-a00f-2eab72af2b1f.png)

I have attached some code that can be used to test.
[test_pk.py.zip](https://github.com/simple-salesforce/simple-salesforce/files/7634362/test_pk.py.zip)

**Comment by jon-wobken** [comment]
Thanks for this. I’ll review and look to merge this Saturday. Looks like this is likely what is causing some of the other issues others are seeing with the bulk job.

**Comment by jon-wobken** [comment]
This if fixed with new release 1.11.5

**Comment by magardner** [comment]
Thanks @jon-wobken for merging this, and for supporting simple-salesforce it is very helpful.
