### ISSUE TITLE
Okta Integration

### ISSUE THREAD

**Issue by Mark-a-Lis** [simple-salesforce/simple-salesforce#519]
Hello! 
My company uses Okta SSO rather than username/passwords. Is there a way I can still use simple-salesforce?
Thanks!

**Comment by hkajiwara** [comment]
After being authenticated via SSO and logging into Salesforce, the user should have a session id. simple_salesforce can leverage the session to connect to the org with _**session_id**_ parameter. (ref. [simple-salesforce](https://pypi.org/project/simple-salesforce/))

**Comment by Mark-a-Lis** [comment]
I keep trying that, using session_ids that I know are valid, and keep getting an invalid session exception. I've checked that I have API permsissions enabled as well. Any ideas?

**Comment by hkajiwara** [comment]
@Mark-a-Lis 

As the error response indicates, it looks like the session is already expired. I would suggest to get authenticated again and to obtain the new one.

**Comment by jon-wobken** [comment]
@Mark-a-Lis - I believe you would need to utilize the JWT token method to authenticate and then generate the session.

To login using the JWT method, use your Salesforce username, consumer key from your app, and private key (How To):

from simple_salesforce import Salesforce
sf = Salesforce(username='myemail@example.com', consumer_key='XYZ', privatekey_file='filename.key')
If you’d like to enter a sandbox, simply add domain='test' to your Salesforce() call.

For example:

from simple_salesforce import Salesforce
sf = Salesforce(username='myemail@example.com.sandbox', password='password', security_token='token', domain='test')
Note that specifying if you want to use a domain is only necessary if you are using the built-in username/password/security token authentication and is used exclusively during the authentication step.

**Comment by tobenary** [comment]
Hi @hkajiwara , All,

I'm a newbie so please try to elaborate on that method.

Assume I'm logged via my OKTA SSO, I am logged through Chrome, I go to the dev tools, and I see the following under the headers cookie:  ( I removed and changed what I thought could lead into a breach )
Is that what you're trying to refer to?

Many thanks!

![chrome_xZlO50L2dW](https://github.com/user-attachments/assets/a5670cdd-feae-41f2-b3b3-820fe522da6f)


```cookie: 
  oid=00Dw0000000DJnB;
  SwitchToClassic=1699274569960;
  CookieConsentPolicy=0:1;
  LSKey-c$CookieConsentPolicy=0:1;
  ApexCSIPageCookie=true;
  rememberUn=true;
  BrowserId_sec=YHSJXXX5wcA;
  com.salesforce.LocaleInfo=us;
  sfdcConsent=1,3,4;
  login=dG9tZXXXXXX51YXQ=;
  LSKey-c$siteUserLanguage=en_US;
  BrowserId=oxfZMXXXXXvA;
  iis_pt=1;
  sid_Client=900000XXXXX00DJnB;
  clientSrc=199.;
  autocomplete=1;
  inst=APP_cW;
  webact={"l_vdays":1,"l_visit":1724151730276,"session":1724154887996,"l_search":"","l_dtype":"SFDC Network","l_page":"SFDC:us:login","l_page_url":"https://c.salesforce.com/login-messages/promos.html","counter":521,"pv":1,"f_visit":1656224284555,"seg":"customer:us","d":"7013000000sUW0","customer":1656269744971,"developer":1679548529493,"trial":1718620435870,"f_form":1718620435870};
  oinfo=c3RhdHVzPUFjdGDAwMERKbkI=;
  sfdc_lv2=KxG83Hp0CALLbVXrZsJf6iXSC9TTPqroSSJqLUogs;
  disco=UW:00DwnB:00560A:1;
  sid=00Dw000000EN45Vn2hms6cTo9Fdzebd6NU.P_..Mbud9Xat2cDvqD53sjqrpD;
  setupopen=;
  ak_bmsc=212F9532B78119D~000000000000000000000000000000~YAAQJjzLx5xC5/GmQXmLbNnZnWjapYaahQ2vea5rOLu/27BodyT4L1Dq3cQV+NaSGC2eq+CdOrikxLSAcwJ1rdy/UxSHfHfxG;
  lastActivePage=1724159378737;
  _abck=E4A4E7C1B08513A0A2AF440037A2D953~0~YAAQPjzLx+fZvmmRAQAAc1Ml7Jah990/VucirkDR9hJu+vsd4Kkcj08mnvXODkUymNiuY/I72fqwMZmMwvaCzPfIqD8t9D+zTB/QTbhoiPyT31r7JY=~-1~-1~-1;
  iis_p=ZjM1MTJhYTUtYWU1Ny00OTMwLTk5ZmYtODI3ZDcyNTk2NzE0ITAwNThXeVRrN1FBRg;
  OptanonConsent=isGpcEnabled=0&datestamp=Tue+Aug+20+2024+17%3A39%3A12+GMT%2B0300+(GMT%2B03%3A00)&version=202401.2.0&browserGpcFlag=0&isIABGlobal=false&hosts=&consentId=f54b6491-0f78-440b-8417-bda80f615cd3&interactionCount=1&landingPath=NotLandingPage&AwaitingReconsent=false&groups=1:1,3:1,4:1;
  bm_sv=AF710E88CB3SvGMJQyzJp/c4tu5/4108=~1;
  alohaEpt=Tue Aug 20 2024 17:42:41 GMT+0300 (GMT+03:00)```

**Comment by tobenary** [comment]
Answering myself: SID is the answer.
