### ISSUE TITLE
simple_salesforce under MFA login with WW-AzureSSO

### ISSUE THREAD

**Issue by P-Rainbow** [simple-salesforce/simple-salesforce#525]
Good day!

My employer is to have users to login Salesforce by Multi Factor Authentication security, from MFA login type with WW-AzureSSO.

Would this affect the use of simple_salesforce with Python?

My usual use is:
`sf = Salesforce(username= “name@user.com” ,password= "password" ,security_token= "token856324125")
sid=sf.session_id`

Thank you.

**Comment by hkajiwara** [comment]
As [the doc](https://help.salesforce.com/s/articleView?id=sf.security_require_2fa_api.htm&type=5) states, if you enable "Multi-Factor Authentication for API Logins", you need to use a security token or TOTP.  It appears the above snippet uses the security token and it would work.

**Comment by P-Rainbow** [comment]
@hkajiwara thank you!
