### ISSUE TITLE
[BUG] Missing fields in object's metadata

### ISSUE THREAD

**Issue by okcze** [simple-salesforce/simple-salesforce#528]
Hi!
I use simple-salesforce for quite some time. Yesterday's new release 1.11.5 in my opinion broke something in metadata extraction. With the new version installed some fields which I'm able to extract with SELECT query are not present in the metadata of the object. However, when I use version 1.11.4 everything is coherent.

Example with 1.11.4:
![obraz](https://user-images.githubusercontent.com/43789503/152181383-b6c4fa15-0d8d-4a50-9b10-16effc79ef66.png)

Example with 1.11.5:
![obraz](https://user-images.githubusercontent.com/43789503/152181418-bb2529ff-db6f-4764-9aec-beb41252457b.png)
The underlined field is missing when using the new version. 
In both version the field can be extracted with SELECT query. Its type in the source is a checkbox.
It occurred for the User object in a few separate SF instances which I daily extract.
Thanks for maintaining the package, it's great, and waiting for some news on the issue!

**Comment by jon-wobken** [comment]
Odd - I can't replicate this when comparing fields. There was no change in the way the describe function works other than the parse_json but even when I query a raw result I don't see any differences.

Can you try setting the version to '42.0' and let me know if you still see this?

from simple_salesforce import Salesforce

sf = Salesforce(username='',password='',
                security_token='')

```
object_desc = sf.User.describe()
object_names = []
for f in object_desc['fields']:
    object_names.append(f['name'])
    print(f['name'])


sf2 = Salesforce(username='',password='',
                security_token='',
                version='42.0')

object_desc2 = sf.User.describe()
object_names2 = []
for f in object_desc['fields']:
    object_names2.append(f['name'])
    print(f['name'])

print(list(set(object_names2)-set(object_names)))
print(list(set(object_names)-set(object_names2)))
```

**Comment by okcze** [comment]
> One additional thought - are you comparing the data between the same org between the versions or different orgs?

I'm comparing on the same org, just changing the package versions.

> Can you try setting the version to '42.0' and let me know if you still see this?

I made the test which you provided:
- the lists of fields are the same for default and 42.0 (empty lists printed in the last 2 lines)
- the "UserPermissionsMobileUser" field is still missing when using package in ver 1.11.5 with both default and 42.0

**Comment by okcze** [comment]
Hi, I checked once again and you're right. I confirm that the difference is caused by api versions:

![diff](https://user-images.githubusercontent.com/43789503/152509626-d2831613-4cac-4299-b8dd-d86ab576b54c.png)

It seems wired to me that they change the content between the versions and they are not backward consistent but anyway that's it. Thanks a lot for help!
