### ISSUE TITLE
Error is thrown on querying CompletedDateTime on task object using sf.Task.query() or usingsf.bulk

### ISSUE THREAD

**Issue by itsme-ram** [simple-salesforce/simple-salesforce#531]
CompletedDateTime is a field on task object, An error is thrown when user queries the field on task object using sf.query.

**Comment by hkajiwara** [comment]
According to [the doc](https://developer.salesforce.com/docs/atlas.en-us.212.0.api.meta/api/sforce_api_objects_task.htm), _**CompletedDateTime**_ field of _Task_ object is not available with older API versions. With a later version, you would be able to retrieve the field data.

`sf = Salesforce(..., version='53.0')`

**Comment by jon-wobken** [comment]
Closed - Salesforce API versions

**Comment by itsme-ram** [comment]
Hi Hiroki,

I have tried the resolution provided by you for setting the version but i
am still getting below error:
simple_salesforce.exceptions.SalesforceGeneralError: Error Code Failed.
Response content: InvalidBatch : Failed to process query: INVALID_FIELD:
select CreatedDateTime from Task where        ^ ERROR at Row:1:Column:8 No
such column 'CreatedDateTime' on entity 'Task'. If you are attempting to
use a custom field, be sure to append the '__c' after the custom field
name. Please reference your WSDL or the describe call for the appropriate
names.

/home/qauser/.local/lib/python3.9/site-packages/simple_salesforce/bulk.py:255:
SalesforceGeneralError

Code used in snippet to define the version:
session_id, instance = SalesforceLogin(username=sf_username, password=
sf_password,
                                            security_token=sf_security_token
)

    sf = Salesforce(session_id=session_id, instance=instance, version =
'53.0')

**Comment by itsme-ram** [comment]
I have also tried with the code:
session_id, instance = SalesforceLogin(username=sf_username, password=
sf_password,
                                            security_token=sf_security_token, sf_version = "53.0"
)

    sf = Salesforce(session_id=session_id, instance=instance)

but still facing the same issue

**Comment by itsme-ram** [comment]
The Query i used is:
select CreatedDateTime from Task
