### ISSUE TITLE
Opportunity Type length different in 1.11.4 vs 1.11.5

### ISSUE THREAD

**Issue by tmontes** [simple-salesforce/simple-salesforce#532]
Hi,

First and foremost, thanks for sharing `simple-salesforce`: it's a wonderful tool I've been using on a few scenarios to grab data from Salesforce.

Scenario:
* Earlier today, I updated one tool to use the recently released version 1.11.5 instead of 1.11.4.
* Among other things, it checks SObject field metadata before proceeding.
* In particular, I'm getting different values for the length of the `Type` field of `Opportunity`.

The minimal reproducible code is:
```
sf = simple_salesforce.Salesforce(...)
length = [
    f['length']
    for f in sf.Opportunity.describe()['fields']
    if f['name'] == 'Type'
]
```

With 1.11.4 `length` comes out as 40 and with 1.11.5 I'm getting 255.

Parting thoughts:
* I understand that metadata code has changed but did not look into it.
* I initially faced this with a production instance, for a client of mine.
* Behaviour is the same on a "plain/vaniall" developer instance.

Wondering if anyone else is experiencing this and, in particular, what ends up being true: 40 or 255?
Happy to collaborate in the diagnostic process.

Thanks again, in advance!

**Comment by jon-wobken** [comment]
@tmontes - I updated the API version in simple-salesforce to 52.0 from 42.0 which is likely the cause. Salesforce implemented some changes in their API version. You can confirm by setting the version field in your login to 42.0 and see if the previous behavior (showing 40 characters).

**Comment by tmontes** [comment]
@jon-wobken, thanks for the ultra-fast response!

I do confirm that I get 40 with 1.11.5, if API 42.0 is used. Any hints as why that might be the case?
(I will go over SF API's change logs, of course!)

Again thanks.
