### ISSUE TITLE
Missing metadata.wsdl in simple-salesforce 1.11.5 Python wheel

### ISSUE THREAD

**Issue by metadaddy** [simple-salesforce/simple-salesforce#533]
I used `pip install` to install simple-salesforce, then tried to use the Metadata API - this error was thrown:

```
E           FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.6/site-packages/simple_salesforce/metadata.wsdl'
```

Investigating, the WSDL is there in GitHub, and in the tarball at https://pypi.org/project/simple-salesforce/#files, but not in the Python wheel. Am I missing something? I don't see any requirement in the docs to download the WSDL separately.

**Comment by jon-wobken** [comment]
Pushed the hotfix for this with v1.11.6
