### ISSUE TITLE
Bulk Import Interface Broken on 1.11.6 on Custom Fields?

### ISSUE THREAD

**Issue by jolson629** [simple-salesforce/simple-salesforce#540]
Tested on simple-salesforce==1.11.6

A bulk insert operation involving a custom field seems to be broken. The error that gets thrown:

```
{'exceptionCode': 'InvalidBatch', 'exceptionMessage': 'Records not processed'}
```

I was originally getting this message trying to bulk insert into a custom object. Through some debugging, I traced the error to trying to bulk insert into a custom field - even if that custom field is in a non-custom object. I run through some test cases in the script below. Am I doing something wrong?

```
from simple_salesforce import Salesforce

salesforce = Salesforce (
            username = <username>,
            password = <password>,
            security_token = <token>,
            domain='test'
        )

mdapi = salesforce.mdapi
url = 'tooling/sobjects/CustomField/'


# Create a custom object
custom_object_name = "TestObject__c"
        
custom_object = mdapi.CustomObject(
        fullName = custom_object_name,
        label = custom_object_name,
        description = "Test debugging object",
        pluralLabel = "Test Objects",
        deploymentStatus = mdapi.DeploymentStatus("Deployed"),
        nameField = mdapi.CustomField(
            label = "TestObjectId",
            type = mdapi.FieldType("AutoNumber")
        ),
        sharingModel = mdapi.SharingModel("ReadWrite")
)

mdapi.CustomObject.create(custom_object)


# Add a custom field to a custom object
payload = {"Metadata": {"type": "Text", "inlineHelpText": "Test text field", "precision": None, "label": "Test", "length": 100, "required": False}, "FullName": "TestObject__c.TestField__c"}

result = salesforce.restful(url, method='POST', json=payload)


# Verify our test object is what we think it is.
custom_object = mdapi.CustomObject.read("TestObject__c")

print(f"""object: {custom_object["fullName"]}""")
for field in custom_object["fields"]:
    print(f"""   field: {field["fullName"]}      type: {field["type"]}      length: {field["length"]}""")


# Add a record to a custom object using the bulk import interface
records = [
    {"TestField__c":"Hello World!"}
]

results = salesforce.bulk.testObject__c.insert(records)                         # {'exceptionCode': 'InvalidBatch', 'exceptionMessage': 'Records not processed'}
results = salesforce.bulk.testObject__c.insert(records, batch_size = 1)         # {'exceptionCode': 'InvalidBatch', 'exceptionMessage': 'Records not processed'}
results = salesforce.bulk.testObject__c.insert(records, batch_size = 10000)     # {'exceptionCode': 'InvalidBatch', 'exceptionMessage': 'Records not processed'}
results = salesforce.bulk.testObject__c.insert(records, use_serial = True)      # {'exceptionCode': 'InvalidBatch', 'exceptionMessage': 'Records not processed'}
print(results)


# Test bulk insert on a non-custom object on a non-custom field. This works as expeted
records = [
    {"Email":"test@somecompany.com", "LastName": "Someguy"}
]

results = salesforce.bulk.Contact.insert(records)  # Success: [{'success': True, 'created': True, 'id': '0037A00000fQ4jqQAC', 'errors': []}]
print(results)



# Test bulk insert on a non-custom object on a custom field

# Add a custom field to Contact object
payload = {"Metadata": {"type": "Text", "inlineHelpText": "Test text field", "precision": None, "label": "Test", "length": 100, "required": False}, "FullName": "Contact.TestField__c"}
result = salesforce.restful(url, method='POST', json=payload)


# Verify it got added
#contact = mdapi.Contact.read()
#print(f"""object: {contact["fullName"]}""")
#for field in contact["fields"]:
#    print(f"""   field: {field["fullName"]}      type: {field["type"]}      length: {field["length"]}""")


# Add record to a custom field in a non-custom object via bulk interface
records = [
    {"TestField__c":"Hello World!"}
]

results = salesforce.bulk.Contact.insert(records)  # {'exceptionCode': 'InvalidBatch', 'exceptionMessage': 'Records not processed'}
print(results)



# Replacing {"TestField__c":"Hello World!"} with {"TestField":"Hello World!"}: {'exceptionCode': 'InvalidBatch', 'exceptionMessage': 'Records not processed'}. Tried many variations, none worked.

```

**Comment by jon-wobken** [comment]
Did you enable allow bulk api on the custom object?

**Comment by jolson629** [comment]
Good point. Didn't know I needed to.

We still have the issue of the custom field in the Contact object throwing the same error.

**Comment by jon-wobken** [comment]
You should be able to set that on the metadata just need to figure out the name I don’t remember it off the top of my head.

Have you downloaded the batch in the UI to see the error message? My guess is you are not including the correct fields/missing a required field on the contact object

**Comment by jolson629** [comment]
I figured out what the problem is. simple_salesforce propelled me into the Salesforce API faster than I was ready for :)

The issue is when you create a custom field (either on a custom object or a non-custom object), you have to set the visibility on the field. Visibility is not a setting on the custom field itself, but on a Salesforce profile. It looks like when you create a custom field using the Salesforce web UI, it gives visibility = Editable to all profiles. When I tried creating it using the CustomField endpoint, visibility = Hidden to all profiles. The endpoint you need to set the visibility of a custom field is the Profile endpoint, as documented in this [StackOverflow](https://salesforce.stackexchange.com/questions/282388/how-to-set-field-visibillty-of-all-custom-fields-in-salesforce-using-metadata-ap) post. UGLY! I have not mastered the Salesforce REST API to the point where I can demo this yet in Python :)

On the Salesforce Lightning web UI, if you pull up an object with a custom field in the Object Manager, go to "Fields & Relationships", pick a custom field, click on the "View Field Accessibilty" button, select the field again in the dropdown box, you'll see the visibility. "Hidden" will throw the error I documented above when trying to bulk insert. "Editable" will allow the bulk API to work. You can flip "Hidden" to "Editable" using a combination of the "View Field Accessibilty" and "Set Field-Level Security" buttons from the edit field page. Both of those buttons will lead to a page where you have to check a 'visible' button, then the field is visible to everyone.

So much for my Saturday.

I'll close this issue out, as it is not a defect with the simple_salesforce release.
