### ISSUE TITLE
Cannot Login From Databricks

### ISSUE THREAD

**Issue by daffyduck25** [simple-salesforce/simple-salesforce#553]
Hello :-)  I have successfully used simple-salesforce locally to connect to Salesforce.  However I am now trying to connect with AWS Databricks and I am getting this error:

SalesforceAuthenticationFailed: INVALID_LOGIN: Invalid username, password, security token; or user locked out.

I have confirmed that all of my login credentials are correct and my account is not locked.

As far as I see from the docs I should be able to use simple-salesforce within Databricks correct?

Here is my connection call (redacted):
sf = Salesforce(username='user@email.com', password=salesforce_pw, security_token=salesforce_token)

Any help is appreciated.

Thanks.

**Comment by hkajiwara** [comment]
[Login History](https://help.salesforce.com/s/articleView?id=sf.users_login_history.htm&type=5) would be helpful to identify the cause of the login failure.

**Comment by jon-wobken** [comment]
The only item in addition to the login history that could be helpful is if they have ip range restrictions applied which could cause the issue
