### ISSUE TITLE
Bulk Upsert support for external IDs in lookup (reference) fields

### ISSUE THREAD

**Issue by jimrae-xede** [simple-salesforce/simple-salesforce#554]
I am trying to use the bulk upsert to load data to a Contact, and reference the external ID for the Account record.
Is this supported?

My code looks roughly like this:

```
data = [
      {'Contact_Guid__c': 'c23ab68b-e5ea-463a-a077-4914af5d5257', 'Lastname':'Smith','Email': 'examplenew2@example.com','AccountId':{'Account_Guid__c':'f5e8ffaa-b7ba-493f-b90d-a63e1871e0ec'}}
    ]

sf.bulk.Contact.upsert(data, 'Contact_Guid__c', batch_size=10000, use_serial=True)
```

With this structure, I get a "JSON Parsing Error", unexpected end of line.  If I quote the entire Account ID value. I get a Malformed ID:
```
data = [
      {'Contact_Guid__c': 'c23ab68b-e5ea-463a-a077-4914af5d5257', 'Lastname':'Smith','Email': 'examplenew2@example.com','AccountId':'{'Account_Guid__c':'f5e8ffaa-b7ba-493f-b90d-a63e1871e0ec'}'}
    ]

sf.bulk.Contact.upsert(data, 'Contact_Guid__c', batch_size=10000, use_serial=True)
```

Any suggestions or recommendations would be appreciated.

**Comment by hkajiwara** [comment]
Looks like _Lookup_ is not supported and you need to specify the valid _AccountId_ which should be 15 or 18 digit as [this doc](https://help.salesforce.com/s/articleView?id=000324087&type=1) says. You would be able to retrieve Account Id like this.

```
record = sf.query("SELECT Id FROM Account WHERE Account_Guid__c = 'f5e8ffaa-b7ba-493f-b90d-a63e1871e0ec' LIMIT 1")
acctId = record['records'][0]['Id']

data = [
        {'Lastname': 'Smith', 'Email': 'examplenew2@example.com', 'AccountId': acctId, 'Contact_Guid__c': 'c23ab68b-e5ea-463a-a077-4914af5d5257'}
    ]
sf.bulk.Contact.upsert(data, 'Contact_Guid__c', batch_size=10000, use_serial=True)
```

**Comment by jon-wobken** [comment]
External ids are supported in that same format, however, you don't have the field formatted correctly. It should be the relationship name not the field so instead of AccountId:{'ext_id':123} it should be Account:{'ext_id':123}
