### ISSUE TITLE
INVALID_LOGIN intermittently

### ISSUE THREAD

**Issue by cfols92** [simple-salesforce/simple-salesforce#561]
We are receiving the `INVALID_LOGIN: Invalid username, password, security token; or user locked out.` exception message intermittently in production when attempting to connect using `Salesforce({'username': config.USERNAME, 'password': config.PASSWORD, 'security_token': config.SECURITY_TOKEN})`.

Python v 3.9.6
simple-salesforce v 1.12.0

I'm able to successfully log in manually using `Salesforce({'username': config.USERNAME, 'password': config.PASSWORD, 'security_token': config.SECURITY_TOKEN})` in both my local and production environments.

I've downloaded my login history from Salesforce and there are no failed login attempts.

I can see the correct username, password, and security token information is being sent to Salesforce when this exception is returned.

This issue first happened July 1 @ 2 am UTC and has been happening randomly since.

Does anyone know what could be going on? Thank you.

**Comment by cfols92** [comment]
Also if this is not the appropriate place to ask this question please point me to where this question would be more appropriate. Thanks

**Comment by jon-wobken** [comment]
@cfols92 - This would be the appropriate spot to ask a question.

I personally haven't experienced this yet. My only though would be if the session is old but if I remember correctly that generates a different error. Is there anything else you can provide (are you on an org that uses whitelisted IPs, is it after the process has been running for a certain amount of time)?

**Comment by cfols92** [comment]
@jon-wobken I discovered some `LOGIN_RATE_EXCEEDED` errors buried in the login history file, so I think that's the problem. I'm going to close this issue. Thanks!
