### ISSUE TITLE
Officially support Python 3.9, 3.10 and 3.11

### ISSUE THREAD

**Issue by edmorley** [simple-salesforce/simple-salesforce#562]
Hi!

Currently this package is only tested against (in CI) and declares support for Python 3.6, 3.7 and 3.8.

https://github.com/simple-salesforce/simple-salesforce/blob/819781c06364ee2c89e8a7783883b6757b36f7f0/.travis.yml#L5-L7
https://github.com/simple-salesforce/simple-salesforce/blob/819781c06364ee2c89e8a7783883b6757b36f7f0/setup.py#L52-L54
https://github.com/simple-salesforce/simple-salesforce/blame/819781c06364ee2c89e8a7783883b6757b36f7f0/README.rst#L12

It would be great to test against (and declare support for) Python 3.9, 3.10 and 3.11 too.

If the size of the test matrix is a concern, then Python 3.6 support could be dropped, given it's now EOL:
https://devguide.python.org/versions/

Many thanks :-)

**Comment by cbailiss** [comment]
Is there an ETA on official support for Python 3.10?  
Are there any known compatibility issues with Python 3.10?

Worth adding that Python 3.11 is also out now.

**Comment by ericbn** [comment]
This was completed with release v1.12.3.
