### ISSUE TITLE
Support for ../api_rest/resources_limits.htm

### ISSUE THREAD

**Issue by RoadRunner88** [simple-salesforce/simple-salesforce#567]
From workbench REST Explorer I am able to query the latest status on Salesforce limits. 

Doc: https://developer.salesforce.com/docs/atlas.en-us.api_rest.meta/api_rest/resources_limits.htm  

Can I use "Using Apex", to make that call and get the response with "Using APEX"?  If so, what would the payload be? 

This is an example in another language: 
req.setEndpoint('https://proofpoint.my.salesforce.com/services/data/v53.0/limits');  with a GET call.

**Comment by syphar** [comment]
have you checked `sf.limits()`? I see it's not in the readme, but it _is_ defined on [`api.Salesforce`](https://github.com/simple-salesforce/simple-salesforce/blob/819781c06364ee2c89e8a7783883b6757b36f7f0/simple_salesforce/api.py#L408-L418).

**Comment by RoadRunner88** [comment]
I will give that a try, thank you
