### ISSUE TITLE
Are there any impacts identified due to Salesforce "Enhanced Domains" feature?

### ISSUE THREAD

**Issue by asif-github** [simple-salesforce/simple-salesforce#573]

**Comment by hkajiwara** [comment]
According to [the doc](https://help.salesforce.com/s/articleView?id=sf.domain_name_enhanced.htm&type=5), Login URL for my domain of Production and Sandbox might be impacted. In case using _login.salesforce.com_ and _test.salesforce.com_, this wouldn't affect.

- Production
_MyDomainName.my.salesforce.com_

- Sandbox
_MyDomainName--SandboxName.sandbox.my.salesforce.com_
