### ISSUE TITLE
How do I use report API with this library?

### ISSUE THREAD

**Issue by zhaoxin** [simple-salesforce/simple-salesforce#58]
For example, How can I run a report with simple_salesforce?
Thanks.

**Comment by ChrisShumaker** [comment]
The short answer is, use the generic restful method:

params = { 'includeDetails' : 'true'}
report = sf.restful('analytics/reports/<your_report_id>', params=params)

Other than that, I do not believe this is supported but at least this saves you from setting up authentication, dealing with request/response objects, and converting to a nicer format like OrderedDict.
