### ISSUE TITLE
AttributeError: 'tuple' object has no attribute 'query_all'

### ISSUE THREAD

**Issue by sampadavb** [simple-salesforce/simple-salesforce#586]
I have installed latest version of simple-salesforce . I am able to connect to org sandbox but while using any attribute I am getting the above mentioned error .

I am able to create '(<simple_salesforce.api.Salesforce object at 0x100c4ca30>,)

**Comment by sampadavb** [comment]
below statement returns tuple instead of object, but in the documentation its given as use sf.query
sf = Salesforce(
            username=user, password=passkey, security_token=tok,
             client_id= 'Refresh_automation_tool',domain='test'),  # returns salseforce object

**Comment by hkajiwara** [comment]
It appears an unnecessary comma is added at the end of the statement. That would cause the issue.

```
...
client_id= 'Refresh_automation_tool',domain='test'), 
```
