### ISSUE TITLE
Escaped password is causing authentication error

### ISSUE THREAD

**Issue by knguyen1** [simple-salesforce/simple-salesforce#600]
**lib ver:** 1.12.2
**api ver:** 52.0

Suppose you have `password&123`, it becomes `password&amp;123` in the payload that gets `POST`ed to the server.

I'm on version 52.0 and it's rejecting escaped passwords.  When I submit the `token_login` call without the escape, it works fine.

The  escapes are here at lines 83 in `simple_salesforce/login.py`:

```
# pylint: disable=E0012,deprecated-method
username = escape(username) if username else None
password = escape(password) if password else None
```

**Comment by hkajiwara** [comment]
_OAuth Username-Password Flow_ would need to use non-escape password value as `token_login()` doesn't log into with SOAP message. I'll submit PR later.

**Comment by Swilder-M** [comment]
> _OAuth Username-Password Flow_ would need to use non-escape password value as `token_login()` doesn't log into with SOAP message. I'll submit PR later.

Hi, Is there any follow-up progress?
