### ISSUE TITLE
Error connecting to Salesforce with newly released simple-salesforce version 1.12.3. 

### ISSUE THREAD

**Issue by zlynch311** [simple-salesforce/simple-salesforce#608]
Here is our stack trace from our lambda function which is trying to connect with Salesforce.

{
"errorMessage": "Algorithm 'RS256' could not be found. Do you have cryptography installed?",
  "errorType": "NotImplementedError",
  "stackTrace": [
    "  File \"/var/task/getCasesFromSalesforce.py\", line 39, in lambda_handler\n    sf = Salesforce(username = 'our@exampleEmail.com', consumer_key='7MVG9ux34Ig8G5ep5hy5numwk919sks9dk20ds44AtFjLvDUXqJrZDrMguICeDkdubXCoFY5U0a', privatekey_file='./private.pem')\n",
    "  File \"/tmp/packages/simple_salesforce/api.py\", line 214, in __init__\n    self._refresh_session()\n",
    "  File \"/tmp/packages/simple_salesforce/api.py\", line 270, in _refresh_session\n    self.session_id, self.sf_instance = self._salesforce_login_partial()\n",
    "  File \"/tmp/packages/simple_salesforce/login.py\", line 182, in SalesforceLogin\n    assertion = jwt.encode(payload, key, algorithm='RS256')\n",
    "  File \"/tmp/packages/jwt/api_jwt.py\", line 67, in encode\n    return api_jws.encode(json_payload, key, algorithm, headers, json_encoder)\n",
    "  File \"/tmp/packages/jwt/api_jws.py\", line 152, in encode\n    alg_obj = self.get_algorithm_by_name(algorithm_)\n",
    "  File \"/tmp/packages/jwt/api_jws.py\", line 91, in get_algorithm_by_name\n    raise NotImplementedError(\n"
  ]
}

simple_salesforce is using the RS256 algorithm to encode our payload. But then the algorithm can't be found and we couldn't log in. We ended up specifying our function to use version 1.12.2 and then everything worked again. I just felt like people should know cus this confused us a bit.

**Comment by ericbn** [comment]
Looks like the `pyjwt` dependency in `setup.py` should be updated to `pyjwt[crypto]`. See https://pyjwt.readthedocs.io/en/stable/installation.html#cryptographic-dependencies-optional

This dependency changed when #537 was merged.

**Comment by jon-wobken** [comment]
Did installing cryptography fix your issue? I have re-released 1.12.3 and included cryptography in the setup.py

**Comment by gunnypatel** [comment]
I don't think the version in pypi has the updated dependency on cryptography.

It just has:
```
[
   'requests>=2.22.0',
   'pyjwt',
   'zeep'
],
```
