### ISSUE TITLE
MFA for API

### ISSUE THREAD

**Issue by lesleyxyz** [simple-salesforce/simple-salesforce#613]
I saw this issue: #525 but couldn't figure out the following
How would I supply the TOPT if [MFA for API](https://help.salesforce.com/s/articleView?language=en_US&id=sf.security_require_2fa_api.htm&type=5) is configured?

```python
sf = Salesforce(username=“name@user.com”, password="password", security_token="<TOTP>")
```
Like this?

**Comment by hkajiwara** [comment]
That is correct. If you use [Salesforce Authenticator](https://help.salesforce.com/s/articleView?id=sf.salesforce_authenticator_totp.htm&type=5), 6-digit token would be generated as TOTP.

**Comment by lesleyxyz** [comment]
Okay thank you, it worked!
