### ISSUE TITLE
Salesforce Platform API Versions 21.0 through 30.0 Retirement

### ISSUE THREAD

**Issue by sablindmitry** [simple-salesforce/simple-salesforce#615]
Just wonder could this retirement somehow affect library or default api version 52 is enough to be outside of these changes?

**Comment by hkajiwara** [comment]
I would say the library is not impacted unless you specify the version lower than 30.
(ref. [Salesforce Platform API Versions 21.0 through 30.0 Retirement](https://help.salesforce.com/s/articleView?id=000389618&type=1))
