### ISSUE TITLE
Can't create custom fields for the `Lead` and `Account` objects

### ISSUE THREAD

**Issue by dalmad2** [simple-salesforce/simple-salesforce#621]
I am trying to create custom fields for the `Lead` and `Account` objects using `simple-salesforce`.

I used the below code to create custom fields for `Lead`.
```python
payload = {
    "Metadata":
        {"type": "Text", "inlineHelpText": "", "precision": None, "label": field, "length": 50, "required": False},
    "FullName": f"lead.{field}"
}

try:
    print(f'Creating Field {field}')
    sf.restful('tooling/sobjects/CustomField/', method='POST', json=payload)
except SalesforceMalformedRequest as e:
    if 'There is already a field named' in e.content[0]['message']:
        print(f"{field} already created.")
    else:
        print(e)
```

It didn't return a warning message. So I executed, `sf.Lead.describe()`. However, it did not return the fields I created using the above code.

What am I doing wrong?

**Comment by hkajiwara** [comment]
The custom field itself is successfully created but it wouldn't be accessible due to [Field-Level Security](https://developer.salesforce.com/docs/atlas.en-us.securityImplGuide.meta/securityImplGuide/admin_fls.htm). Once setting it up appropriately, you would be able to see the field info via `Tooling` or `REST API`.

**Comment by hkajiwara** [comment]
Or, you can see the field info using Metadata API.

```
mdapi = sf.mdapi
acct = mdapi.CustomObject.read('Account')
print(acct)
```

**Comment by dalmad2** [comment]
@hkajiwara Thank you! I was able to resolve my issue. As you said, the custom fields were created. They were not accessible via `sf.Lead.describe()`.
