### ISSUE TITLE
FYI: SOAP API

### ISSUE THREAD

**Issue by jaylenjones** [simple-salesforce/simple-salesforce#624]
With the release of Spring '23 if Enhanced Domain is enabled for your instance, you will not be able to pass the domain as None for `SalesforceLogin`. You will need to use your instance host as the `login.salesforce.com` host will no longer work.

Docs for [Enhanced Domain](https://help.salesforce.com/s/articleView?id=sf.domain_name_enhanced.htm&type=5)

**Comment by hkajiwara** [comment]
According to [Salesforce Enhanced Domains FAQ](https://help.salesforce.com/s/articleView?id=000393816&type=1), both `login.salesforce.com` (for Production) and  `test.salesforce.com` (for Sandbox) should be still available after Enhanced Domain is enabled. Regardless of Enhanced Domain, using My Domain would be recommended though.
