### ISSUE TITLE
how i can bulk insert list object duplicate rule

### ISSUE THREAD

**Issue by trinct1412** [simple-salesforce/simple-salesforce#628]
i read your lib and i saw it's using the api job/batch
but i realized it can't bypass the duplicate rule 
how can i resolve it?
i tried add 'Sforce-Duplicate-Rule-Header': "allowSave=true" into my header but it's not working.

**Comment by reillyholbel** [comment]
You could deactivate the rule (not delete it) salesforce-side temporarily.

**Comment by trinct1412** [comment]
> You could deactivate the rule (not delete it) salesforce-side temporarily.

thank for your help. i solved the problem, close issue
