### ISSUE TITLE
Memory consumption for bulk queryAll operation

### ISSUE THREAD

**Issue by Michae94** [simple-salesforce/simple-salesforce#629]
## Context
In my team, we are ingesting salesforce data using the simple-salesforce library. 
In terms of tech specification, we are using the `queryAll` operation from bulk library to retrieve updated rows of the previous day from a Salesforce object.
This job is running every day.

## Problem
As the table is frequently updated everyday, we are facing memory issue to load the results from the query.
Indeed, we are talking about 100k rows updated everyday with more than 250 columns.
We have a limited memory container to perform this job and we don't want to allocate more memory for this.

## Findings
We found out that all the data retrieved from this Salesforce query were stored in a python object, thus kept in memory. That is where our memory issue was coming from.

## Actions taken
We decided to modify the bulk method, especially the `query_all` part to :
- retrieve data from Salesforce table by chunk (binary split)
- Write and append chunks on a file written on disk (instead of python variable).

This helped us to drastically reduced the memory consumption of this job while not impacting that much the time taken for the job.

## Next step/Suggestions
That being said, for now, we decided to copy the library and manually modified it in our stack. 
Our next steps might be the following : 
- Firstly, anyone already faced this issue ? 
- If so, we may think about cleaning our code and create a MR.

Thanks everyone

**Comment by syphar** [comment]
in the readme there is an example how to fetch bigger amounts of data: 


To retrieve large amounts of data, use

```
query = 'SELECT Id, Name FROM Account'

# generator on the results page
fetch_results = sf.bulk.Account.query(query, lazy_operation=True)

# the generator provides the list of results for every call to next()
all_results = []
for list_results in fetch_results:
  all_results.extend(list_results)
```

Like this you won't have all batches in memory

**Comment by Michae94** [comment]
Thanks, how could I miss this part... 
I'll give it a try 👍

**Comment by Michae94** [comment]
@syphar Hum while implementing this, I did not see any difference between `lazy_operation` activated or not ...
On my side, the fetch_results was only a list of 1 element, containing all the 100k rows.

**Comment by syphar** [comment]
have you tried setting the batch-size to something smaller?

**Comment by Michae94** [comment]
While reading the bulk.py code, I am not sure that the batch-size influences the bulk query if it's a query or queryAll. It seems to be used more for other operations (insert, update etc.)

**Comment by jon-wobken** [comment]
Any reason you are using the bulk api to query instead of the rest api with query_all_iter?

query_all_iter will return a generator to get around the memory error issue.

**Comment by Michae94** [comment]
Hey @jon-wobken , no particular reason. It is a code that has been developed more than 1 year ago, when our tables on Salesforce where not that large.
Thanks for the `query_all_iter` suggestion, I guess it could work as the iteration are done on each record. I will take a look.

From my understanding of the bulk queryAll lazy mode, the lazy part is done on the batches and not on each record itself -> it means that if all your queryAll jobs are done in 1 batch, it does not make any difference (I might be wrong though).
Finally, I did not see how to change the batch size (neither retrieved the batch size default value) with the bulk method. On my case, queryAll job were always done in 1 batch (even with more than 100k records).

**Comment by Michae94** [comment]
Well actually, we use bulk mode to avoid having to do many API calls to Salesforce.
Reading documentation :

> Salesforce Standard API processes up to 200 records in one API call. However, SFDC BULK API processes about 10,000 records in one API call.

**Comment by Michae94** [comment]
What we did on our side was to modify the `call_salesforce` function, especially the request part to set the `stream` parameter at true.
That let us retrieve the results from the request by binary chunk, which we eventually saved as a file on disk.

**Comment by jon-wobken** [comment]
> Well actually, we use bulk mode to avoid having to do many API calls to Salesforce. Reading documentation :
> 
> > Salesforce Standard API processes up to 200 records in one API call. However, SFDC BULK API processes about 10,000 records in one API call.

It actually isn't 200 records in one API call for the query functionality. It is 2,000 records for the query/querymore (https://developer.salesforce.com/docs/atlas.en-us.salesforce_app_limits_cheatsheet.meta/salesforce_app_limits_cheatsheet/salesforce_app_limits_platform_apicalls.htm) unless it contains 2 or more custom long text fields. Typically querying 1 bulk api call = 5 rest API calls so in your case of 100k records it would just be 50 rest api calls unless you have >= 2 custom long text fields. From my experience, the rest api limit is typically high enough that this doesn't impact the rest api limits as it scales with license count. 

I haven't added support for bulk2 api so it is still using bulk1 so query jobs do count against the batch limit. For bulk 2 there is a 24-hour limit of 10k query jobs submitted and total of 1TB of results (https://developer.salesforce.com/docs/atlas.en-us.salesforce_app_limits_cheatsheet.meta/salesforce_app_limits_cheatsheet/salesforce_app_limits_platform_bulkapi.htm) so depending on the amount of data that is being pulled with bulk1 you may hit the batch allocation (15k) or with bulk2 the file size/query limit.

**Comment by Michae94** [comment]
Thanks for this explanation and the clarification of the salesforce limit.
We are way bellow the salesforce API call limit / day so indeed it won't be an issue.

I will check though if we have more than 2 custom long text fields for some of our tables before doing the switch from Bulk API to REST API.

I'll close this for now and reopen it if I found any interesting/sharable findings.
