### ISSUE TITLE
1.12.3 does not include cryptography (when installed from PyPI)

### ISSUE THREAD

**Issue by PierreKiwi** [simple-salesforce/simple-salesforce#641]
Hello simple-salesforce,

It appears that when I install `simple-salesforce` from PyPI, the latest version - `1.12.3` - is not installed with `cryptography` despite being listed in the `install_requires` section of [setup.py](https://github.com/simple-salesforce/simple-salesforce/blob/master/setup.py#L31).

I know that that commit 6e0ab819afed6680b90edf993370ad22bb5bce24 fixes the issue so I am wondering if `1.12.3` has been pushed to PyPI with commit fa3955a73568118c6d1c01a645856e43754799e0 instead.

The workaround is to either install `pyjwt[crypto]` or to install from GitHub directly with

```
pip install git+https://github.com/simple-salesforce/simple-salesforce.git@v1.12.3
```

**Comment by jon-wobken** [comment]
Should be fixed with 1.12.4 with setup.py adding crytography
