### ISSUE TITLE
How To Get The Failed Records In A Batch

### ISSUE THREAD

**Issue by haileyneorsd** [simple-salesforce/simple-salesforce#643]
I'm trying to get some error handling into my script. 

On the Bulk API documentation there's a way to get errors for specific records of a batch (https://developer.salesforce.com/docs/atlas.en-us.api_asynch.meta/api_asynch/asynch_api_batches_failed_records.htm). So if a batch fails you can know which specific records had the error. 

I think, correct me if I'm wrong, the library method to do that is here, line#153 (https://github.com/simple-salesforce/simple-salesforce/blob/fa3955a73568118c6d1c01a645856e43754799e0/simple_salesforce/bulk.py). Does anybody know how to utilize this function to get the failed records in a batch?

  def _get_batch_results(self, job_id, batch_id, operation):
        """ retrieve a set of results from a completed job """

        url = f'{self.bulk_url}job/{job_id}/batch/{batch_id}/result'

        result = call_salesforce(url=url, method='GET', session=self.session,
                                 headers=self.headers)

        if operation in ('query', 'queryAll'):
            for batch_result in result.json():
                url_query_results = f'{url}/{batch_result}'
                batch_query_result = call_salesforce(url=url_query_results,
                                                     method='GET',
                                                     session=self.session,
                                                     headers=self.headers
                                                     ).json()
                yield batch_query_result
        else:
            yield result.json()

**Comment by zhiweio** [comment]
I recommend bulk 2.0 API, official support for getting failed records for ingest jobs, it's easy to use [Get Job Failed Record Results](https://developer.salesforce.com/docs/atlas.en-us.api_asynch.meta/api_asynch/get_job_failed_results.htm)

bulk 2.0 support in this PR #648
