### ISSUE TITLE
Upsert function does not return created ID if a new record is created

### ISSUE THREAD

**Issue by tdambra** [simple-salesforce/simple-salesforce#658]
We're running into an issue where the upsert just returns the REST status code, but we need to the ID of the newly created record

**Comment by jon-wobken** [comment]
@tdambra  - if using the regular api you need to add raw_response=True as a parameter to get the raw JSON response. In addition if you are upserting with an ID then set the ID as the external id (ex.

`result = sf.Account.upsert('Id/005.....',{'FieldApiName__c':'Value'},raw_respone=True)
result.json()`

**Comment by tdambra** [comment]
Thank you!
