### ISSUE TITLE
Add typing annotations

### ISSUE THREAD

**Issue by Shadow-Devil** [simple-salesforce/simple-salesforce#659]
Hi, I wanted to use this awesome library today, but I found out that you are not using any type annotations. 
Is there a reason for this?
I find it more convenient since type annotations kinda "document the code" and help newcomers to use it. It's also nice to get autocomplete in IDEs like PyCharm etc. and could help to find possible type issues.
I would offer to create a PR to add some.

**Comment by jon-wobken** [comment]
Feel free to add them. No current reason why it's not being used just was not historically there and haven't had any time to add them.
