### ISSUE TITLE
No external_id_field in the bulk update method

### ISSUE THREAD

**Issue by DEPT-IDabrowski** [simple-salesforce/simple-salesforce#666]
external_id_field is an argument only in upser method. 
It would be good to also have it in the update method so the records can be updated by the external ID

**Comment by jon-wobken** [comment]
@DEPT-IDabrowski  - This is not supported with Salesforce's bulk api (bulk 1 or 2) as it is only valid for UPSERT operations

https://developer.salesforce.com/docs/atlas.en-us.api_asynch.meta/api_asynch/asynch_api_reference_jobinfo.htm

</body>
</html>
<html>
<body>


Name | Type | Request | Description
-- | -- | -- | --
externalIdFieldName | string | Required with upsert | The name of the external ID field for an upsert().



</body>
</html>
