### ISSUE TITLE
Help Needed - Setting custom Field Permissions

### ISSUE THREAD

**Issue by bvelasquez** [simple-salesforce/simple-salesforce#681]
Hello, thanks in advance for any help. Can the library set field permissions on a custom field. I'm creating a custom field using:

```
mdapi = sf2.mdapi
mdapi.CustomField.create(mdapi.CustomField(...

...

```

This works great. It creates the custom field. But, the Field Level permissions are not set, so I have errors. Is there a way to set the field permissions for the various roles when the field is created, or after?

Thanks!

**Comment by sar009** [comment]
I think I am having similar problems.

I am creating a custom object and field as follows.
```python
custom_object = md_api.CustomObject(
    fullName="my_custom_obj__c",
    label="my_custom_obj",
    pluralLabel="my_custom_obj",
    nameField=md_api.CustomField(
        label="Name",
        type=md_api.FieldType("Text")
    ),
    deploymentStatus=md_api.DeploymentStatus("Deployed"),
    sharingModel=md_api.SharingModel("Read")
)
md_api.CustomObject.create(custom_object)
custom_field = md_api.CustomField(
    fullName=f"my_custom_obj__c.my_custom_fld__c",
    label="my_custom_fld",
    type=md_api.FieldType("Text"),
    length=100
)
md_api.CustomField.create(custom_field)
```

but when describing the object the field is *not available*
```python
sf_api.my_custom_obj__c.describe()
```

but when reading the object the field is *available*
```python
md_api.CustomObject.read('my_custom_obj__c')
```

**Comment by sar009** [comment]
@jon-wobken can you please help here.

**Comment by jon-wobken** [comment]
@sar009 @bvelasquez 

You can add and update OLS and FLS by profile (fullName is the name of the profile, make sure you use the API name of the profile as it might differ then what is in the UI for example "System Administrator" is actually "Admin") doing the following:

```
new_field_fls = [{'name':'CustomObject__c.FieldAPIName__c','editable':True,'readable':True}]
new_object_ols = [{'allowCreate': True,
    'allowDelete': True,
    'allowEdit': True,
    'allowRead': True,
    'modifyAllRecords': True,
    'object': 'CustomObject__c',
    'viewAllRecords': True}]
sf_prod.mdapi.Profile.update(sf_prod.mdapi.Profile(fullName='Admin',fieldPermissions=new_field_fls,objectPermissions=new_object_ols))
```

You could also try to create a custom metadata permission set instead. You can find more info on how to construct that here: https://developer.salesforce.com/docs/atlas.en-us.api_meta.meta/api_meta/meta_permissionset.htm
