### ISSUE TITLE
1.12.5 is not in Pypi

### ISSUE THREAD

**Issue by AlexWerz** [simple-salesforce/simple-salesforce#682]
I am installing Simple-Salesforce with pip and found out that the lastest version on Pypi is still 1.12.4
See here: https://pypi.org/project/simple-salesforce/

Was that on purpose or did something went wrong? I was expecting to get 1.12.5 if I use "latest".

Regards,
Alex

**Comment by jon-wobken** [comment]
Thanks for the heads up. I'll repush it today at some point.

**Comment by sar009** [comment]
1.12.5 is still not available :(

**Comment by jon-wobken** [comment]
This is fixed.
