### ISSUE TITLE
Query All for Bulk API v2

### ISSUE THREAD

**Issue by cbailiss** [simple-salesforce/simple-salesforce#707]
Would it be possible to add support for "query all" to the bulk v2 API query() function in the package?  It looks like a very simple change as most the work is already done...

I see that that the query() function around line 817 in [bulk2.py](https://github.com/simple-salesforce/simple-salesforce/blob/master/simple_salesforce/bulk2.py) supports specifying `Operation.query` (line 837) when calling create_job()  but not `Operation.query_all`.

The underlying create_job() function in bulk2.py looks to already support `Operation.query_all`.  So it looks like "query all" could be added relatively easily to the query() function just by amending the arguments of the query() function.

Would it be possible to add an extra argument (or similar) on the query() function to allow query_all to be used?

**Comment by cbailiss** [comment]
Or alternatively (and to match the function naming for the bulk v1 API), simply copy the query() function, naming it query_all() and change line 837 (in the new function) to be `Operation.query_all`.

**Comment by nauxliu** [comment]
Seems it's been merged 2 weeks ago: https://github.com/simple-salesforce/simple-salesforce/pull/697

**Comment by cbailiss** [comment]
Thanks @nauxliu, I missed that.
