### ISSUE TITLE
1.12.6 is not in Pypi

### ISSUE THREAD

**Issue by pavitra-infocusp** [simple-salesforce/simple-salesforce#715]
I am installing Simple-Salesforce with pip and found out that the lastest version on Pypi is still 1.12.5
See here: https://pypi.org/project/simple-salesforce/

**Comment by gunnypatel** [comment]
@jon-wobken Is there anything we can help with to get the latest version on pypi? Happy to help with anything that you think may be needed.

**Comment by NicoBrg-WDG** [comment]
hi @nickcatal, i saw you were the project's creator on pypi, any chance you could solve this ?

**Comment by stkgo** [comment]
Also interested in this

**Comment by jon-wobken** [comment]
This is now on PyPi @pavitra-infocusp @gunnypatel  @NicoBrg-WDG @stkgo
