### ISSUE TITLE
Any way to get basic schema of underlying database?

### ISSUE THREAD

**Issue by tingofurro** [simple-salesforce/simple-salesforce#725]
Hello,

Simple Salesforce looks amazing.
Since one of the main functionality is to be able to run SoQL queries on the database, is there a way to know what the underlying schema of the database is (what the tables are, and what their fields are) so that I can know the scope of the SoQL queries I can run?

I imagine this is probably use-case dependent, but is there either a programmatic way to get the database schema, or a way to know what a "basic" schema is for a newly created test Salesforce organization?

Thank you very much,
Philippe

**Comment by jon-wobken** [comment]
High level you can use the describe call to get all objects (https://developer.salesforce.com/docs/atlas.en-us.248.0.api.meta/api/sforce_api_calls_describesobjects_describesobjectresult.htm) and then within those get the fields (['fields']), the child relationships (['childRelationships']), or parent relationship (['associateParentEntity']). 

`
sf.describe()

for x in sf.describe()["sobjects"]:
    for i in x['childRelationships']:
        #do something
`

**Comment by tingofurro** [comment]
Thanks so much @jon-wobken this is great!
