### ISSUE TITLE
Difficulty Updating CaseHistory Entries with Specific Timestamps 

### ISSUE THREAD

**Issue by khuangaf** [simple-salesforce/simple-salesforce#746]
Hello,

I'm experiencing an issue while trying to upload data from a local database to Salesforce CRM using the `simple-salesforce` library. Here's the problem:

### Context:
1. **Object**: CaseHistory (read-only object).
2. **Workaround**: Insert entries via the Case object.
3. **What Worked**: I enabled audit field creation permission and successfully inserted cases with backdated `CreatedDate`.

### Problem:
- When I update a case using `sf.Case.update`, I cannot set a custom timestamp for the update.
- As a result, the related entries in CaseHistory show the current timestamp instead of the original timestamp from my local DB.

### Example:
- The top two rows in my CaseHistory table display the current timestamp instead of the desired backdated timestamp.

Is there a way to specify the date of an update when working with the Case object, or another method to achieve the same result?

<img width="1500" alt="image" src="https://github.com/user-attachments/assets/d98d7e89-ac37-4e35-b733-4f63f6900937">

**Comment by williambritt** [comment]
I am not sure this is possible.

The Salesforce documentation for this specifically states `on record creation only`.

https://help.salesforce.com/s/articleView?id=000386699&type=1
