### ISSUE TITLE
Enhancement: Bulk API

### ISSUE THREAD

**Issue by patnaikshekhar** [simple-salesforce/simple-salesforce#76]
Would it be possible to add a provision to use the Bulk API for queries, updates, inserts?

**Comment by demianbrecht** [comment]
Thanks for the suggestion @patnaikshekhar. Given it's REST-based, I wouldn't have any issues with adding support for it at all. Are you interested in contributing a patch?

**Comment by demianbrecht** [comment]
Please see #112 for anyone interesting in picking this up.

**Comment by andscoop** [comment]
Looks like this was handled in #143 . Can always re-open if not everything was covered.
