### ISSUE TITLE
Describe's can't take timeout kwargs.

### ISSUE THREAD

**Issue by andy-corcoran** [simple-salesforce/simple-salesforce#81]
It would be nice to be able to provide the SFType.describe call (https://github.com/heroku/simple-salesforce/blob/master/simple_salesforce/api.py#L134) with a timeout in a similar fashion to other methods(https://github.com/heroku/simple-salesforce/blob/master/simple_salesforce/api.py#L269).

**Comment by banjoh** [comment]
Allow overriding the requests timeout parameter. Best to have it done on instance creation.

**Comment by jon-wobken** [comment]
Merged #342
