### ISSUE TITLE
Require simplejson>=2.1.0 for Python 2.6

### ISSUE THREAD

**Issue by nickcatal** [simple-salesforce/simple-salesforce#88]
Per #87 Python 2.6 requires a version of simplejson that supports the `object_pairs_hook` keyword argument. That functionality was added in simplejson 2.1.0

We'll (probably) need to add to the `if sys.version_info < (2, 7)` test in setup.py `pyver_install_requires.append('simplejson>=2.1.0')`

**Comment by demianbrecht** [comment]
+1, requests should [pick it up automagically](https://github.com/kennethreitz/requests/blob/b8df8911c3591ce1abe823fcde91f6fa4f5ae570/requests/compat.py#L25).

**Comment by demianbrecht** [comment]
Looks like this was fixed in requests (2.6 tests are passing in travis). Closing.
