### ISSUE TITLE
SFType doesn't inherit session.

### ISSUE THREAD

**Issue by dmaone** [simple-salesforce/simple-salesforce#91]
This effectively disables connection pooling and greatly hurts performance.

**Comment by demianbrecht** [comment]
+1, it's been on my radar for a while.

**Comment by dmaone** [comment]
It's one-line fix - pass self.request to the SFType constructor. I did it and it works - but it would be nice not to patch it every time.

**Comment by demianbrecht** [comment]
Yep, functional changes have been blocked as of late while a permanent home was found for the project. Also, not to be overly pedantic, but it's a little more than a one liner when you factor in tests ;)

Feel free to submit a PR though, it would be much appreciated.

**Comment by dmaone** [comment]
Ah, you are the _developer_ of this thing! I thought you were just passing by :)
Will try. It's a bit of a hell here lately, but I'll really try

**Comment by demianbrecht** [comment]
Heh, I'm just a maintainer (not the original author). No rush on the PR, if you get a chance great. We're finalizing some logistics atm and can't merge PRs but I'm hoping to have that cleared up within the next week or so.

**Comment by banjoh** [comment]
+1

**Comment by banjoh** [comment]
Hi guys. Any progress on this issue?

**Comment by demianbrecht** [comment]
@banjoh #98 is an implementation that resolves this. Unfortunately I haven't had the cycles to make the changes/merge. If it's not picked up by anyone else soon, I'm hoping to get to it over the next week or so.

**Comment by banjoh** [comment]
Awesome :D
